## PCRE2 test suite ported from testoutput files.
## Tests are loaded from JSON data files generated by tools/port_pcre2_tests.nim.

import std/[unittest, json, strutils, os]

import ../reni

type
  Pcre2TestKind = enum
    ptkMatch = "match"
    ptkNoMatch = "no_match"

  CaptureGroup = object
    index: int
    value: string

  Pcre2TestCase = object
    kind: Pcre2TestKind
    pattern: string
    flags: string
    subject: string
    groups: seq[CaptureGroup]
    line: int

proc fromHex(hexStr: string): string =
  result = newString(hexStr.len div 2)
  for i in 0 ..< result.len:
    result[i] = chr(parseHexInt(hexStr[i * 2 .. i * 2 + 1]))

proc loadTests(filename: string): seq[Pcre2TestCase] =
  let data = parseJson(readFile(filename))
  result = @[]
  for t in data["tests"]:
    var tc = Pcre2TestCase(
      kind: parseEnum[Pcre2TestKind](t["kind"].getStr),
      pattern: fromHex(t["pattern"].getStr),
      flags: t["flags"].getStr,
      subject: fromHex(t["subject"].getStr),
      line: t["line"].getInt,
    )
    if tc.kind == ptkMatch and t.hasKey("groups"):
      for g in t["groups"]:
        tc.groups.add CaptureGroup(
          index: g["index"].getInt, value: fromHex(g["value"].getStr)
        )
    result.add tc

proc safeDisplay(s: string, maxLen: int = 20): string =
  result = ""
  for ch in s:
    if result.len >= maxLen:
      break
    if ord(ch) >= 32 and ord(ch) < 127:
      result.add ch
    else:
      result.add "\\x" & toHex(ord(ch), 2)

proc parseFlags(flags: string): RegexFlags =
  result = {}
  for ch in flags:
    case ch
    of 'i':
      result.incl rfIgnoreCase
    of 's':
      result.incl rfMultiLine
    of 'm':
      discard # reni always has line-boundary ^/$
    of 'x':
      result.incl rfExtended
    else:
      discard

proc runTestFile(filename: string, suiteName: string) =
  let tests = loadTests(filename)

  var passed, failed, errors: int

  suite suiteName & " (" & $tests.len & " tests)":
    for tc in tests:
      let name =
        $tc.kind & " L" & $tc.line & ": /" & safeDisplay(tc.pattern) & "/" & tc.flags
      test name:
        try:
          let flags = parseFlags(tc.flags)
          case tc.kind
          of ptkMatch:
            let r = re(tc.pattern, flags)
            let m = search(tc.subject, r, stepLimit = 1_000_000)
            if not m.found:
              inc failed
              skip()
            else:
              var groupsOk = true
              for g in tc.groups:
                if g.value == "<unset>":
                  # <unset> means group should NOT be captured
                  if g.index < m.boundaries.len and m.boundaries[g.index].a >= 0:
                    groupsOk = false
                    break
                  continue
                if g.index < m.boundaries.len:
                  let b = m.boundaries[g.index]
                  if b.a >= 0:
                    let got = tc.subject[b.a ..< b.b]
                    if got != g.value:
                      groupsOk = false
                      break
                  else:
                    groupsOk = false
                    break
                else:
                  groupsOk = false
                  break
              if groupsOk:
                inc passed
                check true
              else:
                inc failed
                skip()
          of ptkNoMatch:
            let r = re(tc.pattern, flags)
            let m = search(tc.subject, r, stepLimit = 1_000_000)
            if not m.found:
              inc passed
              check true
            else:
              inc failed
              skip()
        except RegexError:
          inc errors
          skip()
        except RegexLimitError:
          inc errors
          skip()
        except Exception:
          inc errors
          skip()

  echo "\n  Results: ", passed, " passed, ", failed, " wrong, ", errors, " errors"
  echo "  Pass rate (of attempted): ",
    if (passed + failed) > 0:
      $(passed * 100 div (passed + failed))
    else:
      "N/A",
    "%"

when isMainModule:
  let dataDir = currentSourcePath().parentDir / "data"
  runTestFile(dataDir / "pcre2_test1.json", "PCRE2 Test 1 (Basic)")
  runTestFile(dataDir / "pcre2_test2.json", "PCRE2 Test 2 (Extended)")
  runTestFile(dataDir / "pcre2_test4.json", "PCRE2 Test 4 (UTF)")
  runTestFile(dataDir / "pcre2_test7.json", "PCRE2 Test 7 (Unicode Properties)")
