## Oniguruma test suite ported from C test files.
## Tests are loaded from JSON data files generated by tools/port_oniguruma_tests.nim.

import std/[unittest, json, strutils, os]

import ../reni

type
  TestKind = enum
    tkMatch = "x2"
    tkCapture = "x3"
    tkNoMatch = "n"
    tkError = "e"

  OnigTestCase = object
    kind: TestKind
    pattern: string
    subject: string
    fromPos: int
    toPos: int
    mem: int
    errorName: string
    line: int

proc fromHex(hexStr: string): string =
  result = newString(hexStr.len div 2)
  for i in 0 ..< result.len:
    result[i] = chr(parseHexInt(hexStr[i * 2 .. i * 2 + 1]))

proc loadTests(filename: string): seq[OnigTestCase] =
  let data = parseJson(readFile(filename))
  result = @[]
  for t in data["tests"]:
    var tc = OnigTestCase(
      kind: parseEnum[TestKind](t["kind"].getStr),
      pattern: fromHex(t["pattern"].getStr),
      subject: fromHex(t["subject"].getStr),
      line: t["line"].getInt,
    )
    case tc.kind
    of tkMatch:
      tc.fromPos = t["from"].getInt
      tc.toPos = t["to"].getInt
    of tkCapture:
      tc.fromPos = t["from"].getInt
      tc.toPos = t["to"].getInt
      tc.mem = t["mem"].getInt
    of tkNoMatch:
      discard
    of tkError:
      tc.errorName = t["error"].getStr
    result.add tc

proc safeDisplay(s: string, maxLen: int = 20): string =
  ## Create a safe display string for test names
  result = ""
  for ch in s:
    if result.len >= maxLen:
      break
    if ord(ch) >= 32 and ord(ch) < 127:
      result.add ch
    else:
      result.add "\\x" & toHex(ord(ch), 2)

proc runTestFile(filename: string, suiteName: string, backward: bool = false) =
  let tests = loadTests(filename)

  var passed, failed: int

  suite suiteName & " (" & $tests.len & " tests)":
    for tc in tests:
      let name = $tc.kind & " L" & $tc.line & ": /" & safeDisplay(tc.pattern) & "/"
      test name:
        case tc.kind
        of tkMatch:
          try:
            let r = re(tc.pattern)
            let m =
              if backward:
                searchBackward(tc.subject, r)
              else:
                search(tc.subject, r)
            if not m.found:
              checkpoint("expected match but got no match")
              fail()
              inc failed
            elif m.boundaries[0].a != tc.fromPos or m.boundaries[0].b != tc.toPos:
              checkpoint(
                "expected " & $tc.fromPos & "-" & $tc.toPos & " but got " &
                  $m.boundaries[0].a & "-" & $m.boundaries[0].b
              )
              fail()
              inc failed
            else:
              inc passed
          except RegexError:
            checkpoint("parse error: " & getCurrentExceptionMsg())
            fail()
            inc failed
          except:
            checkpoint("unexpected error: " & getCurrentExceptionMsg())
            fail()
            inc failed
        of tkCapture:
          try:
            let r = re(tc.pattern)
            let m =
              if backward:
                searchBackward(tc.subject, r)
              else:
                search(tc.subject, r)
            if not m.found:
              checkpoint("expected match but got no match")
              fail()
              inc failed
            elif tc.mem >= m.boundaries.len:
              checkpoint(
                "capture " & $tc.mem & " not available (only " & $m.boundaries.len & ")"
              )
              fail()
              inc failed
            elif m.boundaries[tc.mem].a != tc.fromPos or
                m.boundaries[tc.mem].b != tc.toPos:
              checkpoint(
                "capture " & $tc.mem & ": expected " & $tc.fromPos & "-" & $tc.toPos &
                  " but got " & $m.boundaries[tc.mem].a & "-" & $m.boundaries[tc.mem].b
              )
              fail()
              inc failed
            else:
              inc passed
          except RegexError:
            checkpoint("parse error: " & getCurrentExceptionMsg())
            fail()
            inc failed
          except:
            checkpoint("unexpected error: " & getCurrentExceptionMsg())
            fail()
            inc failed
        of tkNoMatch:
          try:
            let r = re(tc.pattern)
            let m =
              if backward:
                searchBackward(tc.subject, r)
              else:
                search(tc.subject, r)
            if m.found:
              checkpoint(
                "expected no match but matched at " & $m.boundaries[0].a & "-" &
                  $m.boundaries[0].b
              )
              fail()
              inc failed
            else:
              inc passed
          except RegexError:
            # Parse error on a no-match test - pattern should still be parseable
            checkpoint("parse error: " & getCurrentExceptionMsg())
            fail()
            inc failed
          except:
            checkpoint("unexpected error: " & getCurrentExceptionMsg())
            fail()
            inc failed
        of tkError:
          try:
            discard re(tc.pattern)
            checkpoint("expected error but parsed successfully")
            fail()
            inc failed
          except RegexError:
            inc passed
          except:
            # Other errors also count as "error raised"
            inc passed

  echo "\n  Results: ", passed, " passed, ", failed, " failed"
  echo "  Pass rate: ",
    if (passed + failed) > 0:
      $(passed * 100 div (passed + failed))
    else:
      "N/A",
    "%"
  echo "  Total pass rate: ",
    passed, "/", tests.len, " (", passed * 100 div tests.len, "%)"

when isMainModule:
  let dataDir = currentSourcePath().parentDir / "data"
  runTestFile(dataDir / "oniguruma_utf8.json", "Oniguruma UTF-8 Forward")
  runTestFile(
    dataDir / "oniguruma_back.json", "Oniguruma UTF-8 Backward", backward = true
  )
  runTestFile(dataDir / "oniguruma_syntax.json", "Oniguruma Syntax (Perl/Perl_NG)")
