## Unicode character classification for regex matching.

import std/[unicode, strutils]

import pkg/unicodedb/[scripts, scripts_data, blocks_data]
import pkg/unicodedb/segmentation except wordBreakProp
import pkg/unicodedb/types as udbTypes except unicodeTypes
# All four are wrapped below with a guard against non-code-points.
import pkg/unicodedb/properties except unicodeCategory
import pkg/unicodedb/casing except simpleCaseFold

import types

type
  MultiCharFold* = object
    ## These are characters that fold to multiple characters under case-insensitive matching.
    ## Each entry: (source rune, expansion as seq of runes)
    source*: Rune
    expansion*: seq[Rune]

  RuneBuf* = object
    runes*: array[3, Rune]
    len*: int

  GcbProp* = enum
    ## Grapheme Cluster Break (GCB) property (UAX #29)
    gcbOther
    gcbCR
    gcbLF
    gcbControl
    gcbExtend
    gcbZWJ
    gcbRegionalIndicator
    gcbPrepend
    gcbSpacingMark
    gcbL # Hangul Leading Jamo
    gcbV # Hangul Vowel Jamo
    gcbT # Hangul Trailing Jamo
    gcbLV # Hangul LV Syllable
    gcbLVT # Hangul LVT Syllable

# ``UnicodeDataVersion``, ``UnicodeAssignedCodePoints`` and these ten range
# tables are generated by tools/gen_unicode_tables.py; do not edit by hand:
#
#   EmojiRanges  ExtPictRanges  OtherAlphabeticRanges
#   ControlRanges  ExtendRanges  PrependRanges  SpacingMarkRanges
#   HangulLRanges  HangulVRanges  HangulTRanges
#
# They must come from the same UCD release as the ``unicodedb`` dependency
# (pinned in reni.nimble); tests/test_unicode_data.nim fails on drift.
# The Hangul composition constants and ``MultiCharFolds`` are hand-maintained.
const
  # UCD release the generated tables were built from.
  UnicodeDataVersion* = "17.0.0"
  # Code points whose General_Category is not Cn in ``UnicodeDataVersion``.
  # Serves as the fingerprint of that release.
  UnicodeAssignedCodePoints* = 299382

  # Emoji (emoji-data.txt)
  EmojiRanges*: array[151, (int32, int32)] = [
    (0x0023'i32, 0x0023'i32),
    (0x002A'i32, 0x002A'i32),
    (0x0030'i32, 0x0039'i32),
    (0x00A9'i32, 0x00A9'i32),
    (0x00AE'i32, 0x00AE'i32),
    (0x203C'i32, 0x203C'i32),
    (0x2049'i32, 0x2049'i32),
    (0x2122'i32, 0x2122'i32),
    (0x2139'i32, 0x2139'i32),
    (0x2194'i32, 0x2199'i32),
    (0x21A9'i32, 0x21AA'i32),
    (0x231A'i32, 0x231B'i32),
    (0x2328'i32, 0x2328'i32),
    (0x23CF'i32, 0x23CF'i32),
    (0x23E9'i32, 0x23F3'i32),
    (0x23F8'i32, 0x23FA'i32),
    (0x24C2'i32, 0x24C2'i32),
    (0x25AA'i32, 0x25AB'i32),
    (0x25B6'i32, 0x25B6'i32),
    (0x25C0'i32, 0x25C0'i32),
    (0x25FB'i32, 0x25FE'i32),
    (0x2600'i32, 0x2604'i32),
    (0x260E'i32, 0x260E'i32),
    (0x2611'i32, 0x2611'i32),
    (0x2614'i32, 0x2615'i32),
    (0x2618'i32, 0x2618'i32),
    (0x261D'i32, 0x261D'i32),
    (0x2620'i32, 0x2620'i32),
    (0x2622'i32, 0x2623'i32),
    (0x2626'i32, 0x2626'i32),
    (0x262A'i32, 0x262A'i32),
    (0x262E'i32, 0x262F'i32),
    (0x2638'i32, 0x263A'i32),
    (0x2640'i32, 0x2640'i32),
    (0x2642'i32, 0x2642'i32),
    (0x2648'i32, 0x2653'i32),
    (0x265F'i32, 0x2660'i32),
    (0x2663'i32, 0x2663'i32),
    (0x2665'i32, 0x2666'i32),
    (0x2668'i32, 0x2668'i32),
    (0x267B'i32, 0x267B'i32),
    (0x267E'i32, 0x267F'i32),
    (0x2692'i32, 0x2697'i32),
    (0x2699'i32, 0x2699'i32),
    (0x269B'i32, 0x269C'i32),
    (0x26A0'i32, 0x26A1'i32),
    (0x26A7'i32, 0x26A7'i32),
    (0x26AA'i32, 0x26AB'i32),
    (0x26B0'i32, 0x26B1'i32),
    (0x26BD'i32, 0x26BE'i32),
    (0x26C4'i32, 0x26C5'i32),
    (0x26C8'i32, 0x26C8'i32),
    (0x26CE'i32, 0x26CF'i32),
    (0x26D1'i32, 0x26D1'i32),
    (0x26D3'i32, 0x26D4'i32),
    (0x26E9'i32, 0x26EA'i32),
    (0x26F0'i32, 0x26F5'i32),
    (0x26F7'i32, 0x26FA'i32),
    (0x26FD'i32, 0x26FD'i32),
    (0x2702'i32, 0x2702'i32),
    (0x2705'i32, 0x2705'i32),
    (0x2708'i32, 0x270D'i32),
    (0x270F'i32, 0x270F'i32),
    (0x2712'i32, 0x2712'i32),
    (0x2714'i32, 0x2714'i32),
    (0x2716'i32, 0x2716'i32),
    (0x271D'i32, 0x271D'i32),
    (0x2721'i32, 0x2721'i32),
    (0x2728'i32, 0x2728'i32),
    (0x2733'i32, 0x2734'i32),
    (0x2744'i32, 0x2744'i32),
    (0x2747'i32, 0x2747'i32),
    (0x274C'i32, 0x274C'i32),
    (0x274E'i32, 0x274E'i32),
    (0x2753'i32, 0x2755'i32),
    (0x2757'i32, 0x2757'i32),
    (0x2763'i32, 0x2764'i32),
    (0x2795'i32, 0x2797'i32),
    (0x27A1'i32, 0x27A1'i32),
    (0x27B0'i32, 0x27B0'i32),
    (0x27BF'i32, 0x27BF'i32),
    (0x2934'i32, 0x2935'i32),
    (0x2B05'i32, 0x2B07'i32),
    (0x2B1B'i32, 0x2B1C'i32),
    (0x2B50'i32, 0x2B50'i32),
    (0x2B55'i32, 0x2B55'i32),
    (0x3030'i32, 0x3030'i32),
    (0x303D'i32, 0x303D'i32),
    (0x3297'i32, 0x3297'i32),
    (0x3299'i32, 0x3299'i32),
    (0x1F004'i32, 0x1F004'i32),
    (0x1F0CF'i32, 0x1F0CF'i32),
    (0x1F170'i32, 0x1F171'i32),
    (0x1F17E'i32, 0x1F17F'i32),
    (0x1F18E'i32, 0x1F18E'i32),
    (0x1F191'i32, 0x1F19A'i32),
    (0x1F1E6'i32, 0x1F1FF'i32),
    (0x1F201'i32, 0x1F202'i32),
    (0x1F21A'i32, 0x1F21A'i32),
    (0x1F22F'i32, 0x1F22F'i32),
    (0x1F232'i32, 0x1F23A'i32),
    (0x1F250'i32, 0x1F251'i32),
    (0x1F300'i32, 0x1F321'i32),
    (0x1F324'i32, 0x1F393'i32),
    (0x1F396'i32, 0x1F397'i32),
    (0x1F399'i32, 0x1F39B'i32),
    (0x1F39E'i32, 0x1F3F0'i32),
    (0x1F3F3'i32, 0x1F3F5'i32),
    (0x1F3F7'i32, 0x1F4FD'i32),
    (0x1F4FF'i32, 0x1F53D'i32),
    (0x1F549'i32, 0x1F54E'i32),
    (0x1F550'i32, 0x1F567'i32),
    (0x1F56F'i32, 0x1F570'i32),
    (0x1F573'i32, 0x1F57A'i32),
    (0x1F587'i32, 0x1F587'i32),
    (0x1F58A'i32, 0x1F58D'i32),
    (0x1F590'i32, 0x1F590'i32),
    (0x1F595'i32, 0x1F596'i32),
    (0x1F5A4'i32, 0x1F5A5'i32),
    (0x1F5A8'i32, 0x1F5A8'i32),
    (0x1F5B1'i32, 0x1F5B2'i32),
    (0x1F5BC'i32, 0x1F5BC'i32),
    (0x1F5C2'i32, 0x1F5C4'i32),
    (0x1F5D1'i32, 0x1F5D3'i32),
    (0x1F5DC'i32, 0x1F5DE'i32),
    (0x1F5E1'i32, 0x1F5E1'i32),
    (0x1F5E3'i32, 0x1F5E3'i32),
    (0x1F5E8'i32, 0x1F5E8'i32),
    (0x1F5EF'i32, 0x1F5EF'i32),
    (0x1F5F3'i32, 0x1F5F3'i32),
    (0x1F5FA'i32, 0x1F64F'i32),
    (0x1F680'i32, 0x1F6C5'i32),
    (0x1F6CB'i32, 0x1F6D2'i32),
    (0x1F6D5'i32, 0x1F6D8'i32),
    (0x1F6DC'i32, 0x1F6E5'i32),
    (0x1F6E9'i32, 0x1F6E9'i32),
    (0x1F6EB'i32, 0x1F6EC'i32),
    (0x1F6F0'i32, 0x1F6F0'i32),
    (0x1F6F3'i32, 0x1F6FC'i32),
    (0x1F7E0'i32, 0x1F7EB'i32),
    (0x1F7F0'i32, 0x1F7F0'i32),
    (0x1F90C'i32, 0x1F93A'i32),
    (0x1F93C'i32, 0x1F945'i32),
    (0x1F947'i32, 0x1F9FF'i32),
    (0x1FA70'i32, 0x1FA7C'i32),
    (0x1FA80'i32, 0x1FA8A'i32),
    (0x1FA8E'i32, 0x1FAC6'i32),
    (0x1FAC8'i32, 0x1FAC8'i32),
    (0x1FACD'i32, 0x1FADC'i32),
    (0x1FADF'i32, 0x1FAEA'i32),
    (0x1FAEF'i32, 0x1FAF8'i32),
  ]

  # Extended_Pictographic (emoji-data.txt)
  ExtPictRanges*: array[156, (int32, int32)] = [
    (0x00A9'i32, 0x00A9'i32),
    (0x00AE'i32, 0x00AE'i32),
    (0x203C'i32, 0x203C'i32),
    (0x2049'i32, 0x2049'i32),
    (0x2122'i32, 0x2122'i32),
    (0x2139'i32, 0x2139'i32),
    (0x2194'i32, 0x2199'i32),
    (0x21A9'i32, 0x21AA'i32),
    (0x231A'i32, 0x231B'i32),
    (0x2328'i32, 0x2328'i32),
    (0x23CF'i32, 0x23CF'i32),
    (0x23E9'i32, 0x23F3'i32),
    (0x23F8'i32, 0x23FA'i32),
    (0x24C2'i32, 0x24C2'i32),
    (0x25AA'i32, 0x25AB'i32),
    (0x25B6'i32, 0x25B6'i32),
    (0x25C0'i32, 0x25C0'i32),
    (0x25FB'i32, 0x25FE'i32),
    (0x2600'i32, 0x2604'i32),
    (0x260E'i32, 0x260E'i32),
    (0x2611'i32, 0x2611'i32),
    (0x2614'i32, 0x2615'i32),
    (0x2618'i32, 0x2618'i32),
    (0x261D'i32, 0x261D'i32),
    (0x2620'i32, 0x2620'i32),
    (0x2622'i32, 0x2623'i32),
    (0x2626'i32, 0x2626'i32),
    (0x262A'i32, 0x262A'i32),
    (0x262E'i32, 0x262F'i32),
    (0x2638'i32, 0x263A'i32),
    (0x2640'i32, 0x2640'i32),
    (0x2642'i32, 0x2642'i32),
    (0x2648'i32, 0x2653'i32),
    (0x265F'i32, 0x2660'i32),
    (0x2663'i32, 0x2663'i32),
    (0x2665'i32, 0x2666'i32),
    (0x2668'i32, 0x2668'i32),
    (0x267B'i32, 0x267B'i32),
    (0x267E'i32, 0x267F'i32),
    (0x2692'i32, 0x2697'i32),
    (0x2699'i32, 0x2699'i32),
    (0x269B'i32, 0x269C'i32),
    (0x26A0'i32, 0x26A1'i32),
    (0x26A7'i32, 0x26A7'i32),
    (0x26AA'i32, 0x26AB'i32),
    (0x26B0'i32, 0x26B1'i32),
    (0x26BD'i32, 0x26BE'i32),
    (0x26C4'i32, 0x26C5'i32),
    (0x26C8'i32, 0x26C8'i32),
    (0x26CE'i32, 0x26CF'i32),
    (0x26D1'i32, 0x26D1'i32),
    (0x26D3'i32, 0x26D4'i32),
    (0x26E9'i32, 0x26EA'i32),
    (0x26F0'i32, 0x26F5'i32),
    (0x26F7'i32, 0x26FA'i32),
    (0x26FD'i32, 0x26FD'i32),
    (0x2702'i32, 0x2702'i32),
    (0x2705'i32, 0x2705'i32),
    (0x2708'i32, 0x270D'i32),
    (0x270F'i32, 0x270F'i32),
    (0x2712'i32, 0x2712'i32),
    (0x2714'i32, 0x2714'i32),
    (0x2716'i32, 0x2716'i32),
    (0x271D'i32, 0x271D'i32),
    (0x2721'i32, 0x2721'i32),
    (0x2728'i32, 0x2728'i32),
    (0x2733'i32, 0x2734'i32),
    (0x2744'i32, 0x2744'i32),
    (0x2747'i32, 0x2747'i32),
    (0x274C'i32, 0x274C'i32),
    (0x274E'i32, 0x274E'i32),
    (0x2753'i32, 0x2755'i32),
    (0x2757'i32, 0x2757'i32),
    (0x2763'i32, 0x2764'i32),
    (0x2795'i32, 0x2797'i32),
    (0x27A1'i32, 0x27A1'i32),
    (0x27B0'i32, 0x27B0'i32),
    (0x27BF'i32, 0x27BF'i32),
    (0x2934'i32, 0x2935'i32),
    (0x2B05'i32, 0x2B07'i32),
    (0x2B1B'i32, 0x2B1C'i32),
    (0x2B50'i32, 0x2B50'i32),
    (0x2B55'i32, 0x2B55'i32),
    (0x3030'i32, 0x3030'i32),
    (0x303D'i32, 0x303D'i32),
    (0x3297'i32, 0x3297'i32),
    (0x3299'i32, 0x3299'i32),
    (0x1F004'i32, 0x1F004'i32),
    (0x1F02C'i32, 0x1F02F'i32),
    (0x1F094'i32, 0x1F09F'i32),
    (0x1F0AF'i32, 0x1F0B0'i32),
    (0x1F0C0'i32, 0x1F0C0'i32),
    (0x1F0CF'i32, 0x1F0D0'i32),
    (0x1F0F6'i32, 0x1F0FF'i32),
    (0x1F170'i32, 0x1F171'i32),
    (0x1F17E'i32, 0x1F17F'i32),
    (0x1F18E'i32, 0x1F18E'i32),
    (0x1F191'i32, 0x1F19A'i32),
    (0x1F1AE'i32, 0x1F1E5'i32),
    (0x1F201'i32, 0x1F20F'i32),
    (0x1F21A'i32, 0x1F21A'i32),
    (0x1F22F'i32, 0x1F22F'i32),
    (0x1F232'i32, 0x1F23A'i32),
    (0x1F23C'i32, 0x1F23F'i32),
    (0x1F249'i32, 0x1F25F'i32),
    (0x1F266'i32, 0x1F321'i32),
    (0x1F324'i32, 0x1F393'i32),
    (0x1F396'i32, 0x1F397'i32),
    (0x1F399'i32, 0x1F39B'i32),
    (0x1F39E'i32, 0x1F3F0'i32),
    (0x1F3F3'i32, 0x1F3F5'i32),
    (0x1F3F7'i32, 0x1F3FA'i32),
    (0x1F400'i32, 0x1F4FD'i32),
    (0x1F4FF'i32, 0x1F53D'i32),
    (0x1F549'i32, 0x1F54E'i32),
    (0x1F550'i32, 0x1F567'i32),
    (0x1F56F'i32, 0x1F570'i32),
    (0x1F573'i32, 0x1F57A'i32),
    (0x1F587'i32, 0x1F587'i32),
    (0x1F58A'i32, 0x1F58D'i32),
    (0x1F590'i32, 0x1F590'i32),
    (0x1F595'i32, 0x1F596'i32),
    (0x1F5A4'i32, 0x1F5A5'i32),
    (0x1F5A8'i32, 0x1F5A8'i32),
    (0x1F5B1'i32, 0x1F5B2'i32),
    (0x1F5BC'i32, 0x1F5BC'i32),
    (0x1F5C2'i32, 0x1F5C4'i32),
    (0x1F5D1'i32, 0x1F5D3'i32),
    (0x1F5DC'i32, 0x1F5DE'i32),
    (0x1F5E1'i32, 0x1F5E1'i32),
    (0x1F5E3'i32, 0x1F5E3'i32),
    (0x1F5E8'i32, 0x1F5E8'i32),
    (0x1F5EF'i32, 0x1F5EF'i32),
    (0x1F5F3'i32, 0x1F5F3'i32),
    (0x1F5FA'i32, 0x1F64F'i32),
    (0x1F680'i32, 0x1F6C5'i32),
    (0x1F6CB'i32, 0x1F6D2'i32),
    (0x1F6D5'i32, 0x1F6E5'i32),
    (0x1F6E9'i32, 0x1F6E9'i32),
    (0x1F6EB'i32, 0x1F6F0'i32),
    (0x1F6F3'i32, 0x1F6FF'i32),
    (0x1F7DA'i32, 0x1F7FF'i32),
    (0x1F80C'i32, 0x1F80F'i32),
    (0x1F848'i32, 0x1F84F'i32),
    (0x1F85A'i32, 0x1F85F'i32),
    (0x1F888'i32, 0x1F88F'i32),
    (0x1F8AE'i32, 0x1F8AF'i32),
    (0x1F8BC'i32, 0x1F8BF'i32),
    (0x1F8C2'i32, 0x1F8CF'i32),
    (0x1F8D9'i32, 0x1F8FF'i32),
    (0x1F90C'i32, 0x1F93A'i32),
    (0x1F93C'i32, 0x1F945'i32),
    (0x1F947'i32, 0x1F9FF'i32),
    (0x1FA58'i32, 0x1FA5F'i32),
    (0x1FA6E'i32, 0x1FAFF'i32),
    (0x1FC00'i32, 0x1FFFD'i32),
  ]

  # Other_Alphabetic (PropList.txt). Used by POSIX/Oniguruma Alpha:
  # Alphabetic = L ∪ Nl ∪ Other_Alphabetic.
  OtherAlphabeticRanges*: array[255, (int32, int32)] = [
    (0x0345'i32, 0x0345'i32),
    (0x0363'i32, 0x036F'i32),
    (0x05B0'i32, 0x05BD'i32),
    (0x05BF'i32, 0x05BF'i32),
    (0x05C1'i32, 0x05C2'i32),
    (0x05C4'i32, 0x05C5'i32),
    (0x05C7'i32, 0x05C7'i32),
    (0x0610'i32, 0x061A'i32),
    (0x064B'i32, 0x0657'i32),
    (0x0659'i32, 0x065F'i32),
    (0x0670'i32, 0x0670'i32),
    (0x06D6'i32, 0x06DC'i32),
    (0x06E1'i32, 0x06E4'i32),
    (0x06E7'i32, 0x06E8'i32),
    (0x06ED'i32, 0x06ED'i32),
    (0x0711'i32, 0x0711'i32),
    (0x0730'i32, 0x073F'i32),
    (0x07A6'i32, 0x07B0'i32),
    (0x0816'i32, 0x0817'i32),
    (0x081B'i32, 0x0823'i32),
    (0x0825'i32, 0x0827'i32),
    (0x0829'i32, 0x082C'i32),
    (0x0897'i32, 0x0897'i32),
    (0x08D4'i32, 0x08DF'i32),
    (0x08E3'i32, 0x08E9'i32),
    (0x08F0'i32, 0x0903'i32),
    (0x093A'i32, 0x093B'i32),
    (0x093E'i32, 0x094C'i32),
    (0x094E'i32, 0x094F'i32),
    (0x0955'i32, 0x0957'i32),
    (0x0962'i32, 0x0963'i32),
    (0x0981'i32, 0x0983'i32),
    (0x09BE'i32, 0x09C4'i32),
    (0x09C7'i32, 0x09C8'i32),
    (0x09CB'i32, 0x09CC'i32),
    (0x09D7'i32, 0x09D7'i32),
    (0x09E2'i32, 0x09E3'i32),
    (0x0A01'i32, 0x0A03'i32),
    (0x0A3E'i32, 0x0A42'i32),
    (0x0A47'i32, 0x0A48'i32),
    (0x0A4B'i32, 0x0A4C'i32),
    (0x0A51'i32, 0x0A51'i32),
    (0x0A70'i32, 0x0A71'i32),
    (0x0A75'i32, 0x0A75'i32),
    (0x0A81'i32, 0x0A83'i32),
    (0x0ABE'i32, 0x0AC5'i32),
    (0x0AC7'i32, 0x0AC9'i32),
    (0x0ACB'i32, 0x0ACC'i32),
    (0x0AE2'i32, 0x0AE3'i32),
    (0x0AFA'i32, 0x0AFC'i32),
    (0x0B01'i32, 0x0B03'i32),
    (0x0B3E'i32, 0x0B44'i32),
    (0x0B47'i32, 0x0B48'i32),
    (0x0B4B'i32, 0x0B4C'i32),
    (0x0B56'i32, 0x0B57'i32),
    (0x0B62'i32, 0x0B63'i32),
    (0x0B82'i32, 0x0B82'i32),
    (0x0BBE'i32, 0x0BC2'i32),
    (0x0BC6'i32, 0x0BC8'i32),
    (0x0BCA'i32, 0x0BCC'i32),
    (0x0BD7'i32, 0x0BD7'i32),
    (0x0C00'i32, 0x0C04'i32),
    (0x0C3E'i32, 0x0C44'i32),
    (0x0C46'i32, 0x0C48'i32),
    (0x0C4A'i32, 0x0C4C'i32),
    (0x0C55'i32, 0x0C56'i32),
    (0x0C62'i32, 0x0C63'i32),
    (0x0C81'i32, 0x0C83'i32),
    (0x0CBE'i32, 0x0CC4'i32),
    (0x0CC6'i32, 0x0CC8'i32),
    (0x0CCA'i32, 0x0CCC'i32),
    (0x0CD5'i32, 0x0CD6'i32),
    (0x0CE2'i32, 0x0CE3'i32),
    (0x0CF3'i32, 0x0CF3'i32),
    (0x0D00'i32, 0x0D03'i32),
    (0x0D3E'i32, 0x0D44'i32),
    (0x0D46'i32, 0x0D48'i32),
    (0x0D4A'i32, 0x0D4C'i32),
    (0x0D57'i32, 0x0D57'i32),
    (0x0D62'i32, 0x0D63'i32),
    (0x0D81'i32, 0x0D83'i32),
    (0x0DCF'i32, 0x0DD4'i32),
    (0x0DD6'i32, 0x0DD6'i32),
    (0x0DD8'i32, 0x0DDF'i32),
    (0x0DF2'i32, 0x0DF3'i32),
    (0x0E31'i32, 0x0E31'i32),
    (0x0E34'i32, 0x0E3A'i32),
    (0x0E4D'i32, 0x0E4D'i32),
    (0x0EB1'i32, 0x0EB1'i32),
    (0x0EB4'i32, 0x0EB9'i32),
    (0x0EBB'i32, 0x0EBC'i32),
    (0x0ECD'i32, 0x0ECD'i32),
    (0x0F71'i32, 0x0F83'i32),
    (0x0F8D'i32, 0x0F97'i32),
    (0x0F99'i32, 0x0FBC'i32),
    (0x102B'i32, 0x1036'i32),
    (0x1038'i32, 0x1038'i32),
    (0x103B'i32, 0x103E'i32),
    (0x1056'i32, 0x1059'i32),
    (0x105E'i32, 0x1060'i32),
    (0x1062'i32, 0x1064'i32),
    (0x1067'i32, 0x106D'i32),
    (0x1071'i32, 0x1074'i32),
    (0x1082'i32, 0x108D'i32),
    (0x108F'i32, 0x108F'i32),
    (0x109A'i32, 0x109D'i32),
    (0x1712'i32, 0x1713'i32),
    (0x1732'i32, 0x1733'i32),
    (0x1752'i32, 0x1753'i32),
    (0x1772'i32, 0x1773'i32),
    (0x17B6'i32, 0x17C8'i32),
    (0x1885'i32, 0x1886'i32),
    (0x18A9'i32, 0x18A9'i32),
    (0x1920'i32, 0x192B'i32),
    (0x1930'i32, 0x1938'i32),
    (0x1A17'i32, 0x1A1B'i32),
    (0x1A55'i32, 0x1A5E'i32),
    (0x1A61'i32, 0x1A74'i32),
    (0x1ABF'i32, 0x1AC0'i32),
    (0x1ACC'i32, 0x1ACE'i32),
    (0x1B00'i32, 0x1B04'i32),
    (0x1B35'i32, 0x1B43'i32),
    (0x1B80'i32, 0x1B82'i32),
    (0x1BA1'i32, 0x1BA9'i32),
    (0x1BAC'i32, 0x1BAD'i32),
    (0x1BE7'i32, 0x1BF1'i32),
    (0x1C24'i32, 0x1C36'i32),
    (0x1DD3'i32, 0x1DF4'i32),
    (0x24B6'i32, 0x24E9'i32),
    (0x2DE0'i32, 0x2DFF'i32),
    (0xA674'i32, 0xA67B'i32),
    (0xA69E'i32, 0xA69F'i32),
    (0xA802'i32, 0xA802'i32),
    (0xA80B'i32, 0xA80B'i32),
    (0xA823'i32, 0xA827'i32),
    (0xA880'i32, 0xA881'i32),
    (0xA8B4'i32, 0xA8C3'i32),
    (0xA8C5'i32, 0xA8C5'i32),
    (0xA8FF'i32, 0xA8FF'i32),
    (0xA926'i32, 0xA92A'i32),
    (0xA947'i32, 0xA952'i32),
    (0xA980'i32, 0xA983'i32),
    (0xA9B4'i32, 0xA9BF'i32),
    (0xA9E5'i32, 0xA9E5'i32),
    (0xAA29'i32, 0xAA36'i32),
    (0xAA43'i32, 0xAA43'i32),
    (0xAA4C'i32, 0xAA4D'i32),
    (0xAA7B'i32, 0xAA7D'i32),
    (0xAAB0'i32, 0xAAB0'i32),
    (0xAAB2'i32, 0xAAB4'i32),
    (0xAAB7'i32, 0xAAB8'i32),
    (0xAABE'i32, 0xAABE'i32),
    (0xAAEB'i32, 0xAAEF'i32),
    (0xAAF5'i32, 0xAAF5'i32),
    (0xABE3'i32, 0xABEA'i32),
    (0xFB1E'i32, 0xFB1E'i32),
    (0x10376'i32, 0x1037A'i32),
    (0x10A01'i32, 0x10A03'i32),
    (0x10A05'i32, 0x10A06'i32),
    (0x10A0C'i32, 0x10A0F'i32),
    (0x10D24'i32, 0x10D27'i32),
    (0x10D69'i32, 0x10D69'i32),
    (0x10EAB'i32, 0x10EAC'i32),
    (0x10EFA'i32, 0x10EFC'i32),
    (0x11000'i32, 0x11002'i32),
    (0x11038'i32, 0x11045'i32),
    (0x11073'i32, 0x11074'i32),
    (0x11080'i32, 0x11082'i32),
    (0x110B0'i32, 0x110B8'i32),
    (0x110C2'i32, 0x110C2'i32),
    (0x11100'i32, 0x11102'i32),
    (0x11127'i32, 0x11132'i32),
    (0x11145'i32, 0x11146'i32),
    (0x11180'i32, 0x11182'i32),
    (0x111B3'i32, 0x111BF'i32),
    (0x111CE'i32, 0x111CF'i32),
    (0x1122C'i32, 0x11234'i32),
    (0x11237'i32, 0x11237'i32),
    (0x1123E'i32, 0x1123E'i32),
    (0x11241'i32, 0x11241'i32),
    (0x112DF'i32, 0x112E8'i32),
    (0x11300'i32, 0x11303'i32),
    (0x1133E'i32, 0x11344'i32),
    (0x11347'i32, 0x11348'i32),
    (0x1134B'i32, 0x1134C'i32),
    (0x11357'i32, 0x11357'i32),
    (0x11362'i32, 0x11363'i32),
    (0x113B8'i32, 0x113C0'i32),
    (0x113C2'i32, 0x113C2'i32),
    (0x113C5'i32, 0x113C5'i32),
    (0x113C7'i32, 0x113CA'i32),
    (0x113CC'i32, 0x113CD'i32),
    (0x11435'i32, 0x11441'i32),
    (0x11443'i32, 0x11445'i32),
    (0x114B0'i32, 0x114C1'i32),
    (0x115AF'i32, 0x115B5'i32),
    (0x115B8'i32, 0x115BE'i32),
    (0x115DC'i32, 0x115DD'i32),
    (0x11630'i32, 0x1163E'i32),
    (0x11640'i32, 0x11640'i32),
    (0x116AB'i32, 0x116B5'i32),
    (0x1171D'i32, 0x1172A'i32),
    (0x1182C'i32, 0x11838'i32),
    (0x11930'i32, 0x11935'i32),
    (0x11937'i32, 0x11938'i32),
    (0x1193B'i32, 0x1193C'i32),
    (0x11940'i32, 0x11940'i32),
    (0x11942'i32, 0x11942'i32),
    (0x119D1'i32, 0x119D7'i32),
    (0x119DA'i32, 0x119DF'i32),
    (0x119E4'i32, 0x119E4'i32),
    (0x11A01'i32, 0x11A0A'i32),
    (0x11A35'i32, 0x11A39'i32),
    (0x11A3B'i32, 0x11A3E'i32),
    (0x11A51'i32, 0x11A5B'i32),
    (0x11A8A'i32, 0x11A97'i32),
    (0x11B60'i32, 0x11B67'i32),
    (0x11C2F'i32, 0x11C36'i32),
    (0x11C38'i32, 0x11C3E'i32),
    (0x11C92'i32, 0x11CA7'i32),
    (0x11CA9'i32, 0x11CB6'i32),
    (0x11D31'i32, 0x11D36'i32),
    (0x11D3A'i32, 0x11D3A'i32),
    (0x11D3C'i32, 0x11D3D'i32),
    (0x11D3F'i32, 0x11D41'i32),
    (0x11D43'i32, 0x11D43'i32),
    (0x11D47'i32, 0x11D47'i32),
    (0x11D8A'i32, 0x11D8E'i32),
    (0x11D90'i32, 0x11D91'i32),
    (0x11D93'i32, 0x11D96'i32),
    (0x11EF3'i32, 0x11EF6'i32),
    (0x11F00'i32, 0x11F01'i32),
    (0x11F03'i32, 0x11F03'i32),
    (0x11F34'i32, 0x11F3A'i32),
    (0x11F3E'i32, 0x11F40'i32),
    (0x1611E'i32, 0x1612E'i32),
    (0x16F4F'i32, 0x16F4F'i32),
    (0x16F51'i32, 0x16F87'i32),
    (0x16F8F'i32, 0x16F92'i32),
    (0x16FF0'i32, 0x16FF1'i32),
    (0x1BC9E'i32, 0x1BC9E'i32),
    (0x1E000'i32, 0x1E006'i32),
    (0x1E008'i32, 0x1E018'i32),
    (0x1E01B'i32, 0x1E021'i32),
    (0x1E023'i32, 0x1E024'i32),
    (0x1E026'i32, 0x1E02A'i32),
    (0x1E08F'i32, 0x1E08F'i32),
    (0x1E6E3'i32, 0x1E6E3'i32),
    (0x1E6E6'i32, 0x1E6E6'i32),
    (0x1E6EE'i32, 0x1E6EF'i32),
    (0x1E6F5'i32, 0x1E6F5'i32),
    (0x1E947'i32, 0x1E947'i32),
    (0x1F130'i32, 0x1F149'i32),
    (0x1F150'i32, 0x1F169'i32),
    (0x1F170'i32, 0x1F189'i32),
  ]

  # Hangul syllable composition (UAX #15).  These describe the precomposed
  # AC00..D7A3 block and drive the GCB=LV/LVT split below; they are NOT the
  # GCB=L/V/T jamo ranges, which are wider and live in the tables above.
  HangulSBase = 0xAC00
  HangulLCount = 19
  HangulVCount = 21
  HangulTCount = 28
  HangulNCount = HangulVCount * HangulTCount # 588
  HangulSCount = HangulLCount * HangulNCount # 11172

  # Grapheme_Cluster_Break=Control (GraphemeBreakProperty.txt): Cc, Zl, Zp,
  # the Cf characters that are neither Prepend nor ZWJ/ZWNJ, and the
  # unassigned code points that default to Default_Ignorable_Code_Point.
  ControlRanges: array[19, (int32, int32)] = [
    (0x0000'i32, 0x0009'i32),
    (0x000B'i32, 0x000C'i32),
    (0x000E'i32, 0x001F'i32),
    (0x007F'i32, 0x009F'i32),
    (0x00AD'i32, 0x00AD'i32),
    (0x061C'i32, 0x061C'i32),
    (0x180E'i32, 0x180E'i32),
    (0x200B'i32, 0x200B'i32),
    (0x200E'i32, 0x200F'i32),
    (0x2028'i32, 0x202E'i32),
    (0x2060'i32, 0x206F'i32),
    (0xFEFF'i32, 0xFEFF'i32),
    (0xFFF0'i32, 0xFFFB'i32),
    (0x13430'i32, 0x1343F'i32),
    (0x1BCA0'i32, 0x1BCA3'i32),
    (0x1D173'i32, 0x1D17A'i32),
    (0xE0000'i32, 0xE001F'i32),
    (0xE0080'i32, 0xE00FF'i32),
    (0xE01F0'i32, 0xE0FFF'i32),
  ]

  # Grapheme_Cluster_Break=Extend (GraphemeBreakProperty.txt): Grapheme_Extend
  # plus Emoji_Modifier and the tag characters.  Not derivable from the general
  # category (31 Mc characters are neither Extend nor SpacingMark, and
  # U+1F3FB..U+1F3FF / U+FF9E..U+FF9F are Extend without being marks).
  ExtendRanges: array[384, (int32, int32)] = [
    (0x0300'i32, 0x036F'i32),
    (0x0483'i32, 0x0489'i32),
    (0x0591'i32, 0x05BD'i32),
    (0x05BF'i32, 0x05BF'i32),
    (0x05C1'i32, 0x05C2'i32),
    (0x05C4'i32, 0x05C5'i32),
    (0x05C7'i32, 0x05C7'i32),
    (0x0610'i32, 0x061A'i32),
    (0x064B'i32, 0x065F'i32),
    (0x0670'i32, 0x0670'i32),
    (0x06D6'i32, 0x06DC'i32),
    (0x06DF'i32, 0x06E4'i32),
    (0x06E7'i32, 0x06E8'i32),
    (0x06EA'i32, 0x06ED'i32),
    (0x0711'i32, 0x0711'i32),
    (0x0730'i32, 0x074A'i32),
    (0x07A6'i32, 0x07B0'i32),
    (0x07EB'i32, 0x07F3'i32),
    (0x07FD'i32, 0x07FD'i32),
    (0x0816'i32, 0x0819'i32),
    (0x081B'i32, 0x0823'i32),
    (0x0825'i32, 0x0827'i32),
    (0x0829'i32, 0x082D'i32),
    (0x0859'i32, 0x085B'i32),
    (0x0897'i32, 0x089F'i32),
    (0x08CA'i32, 0x08E1'i32),
    (0x08E3'i32, 0x0902'i32),
    (0x093A'i32, 0x093A'i32),
    (0x093C'i32, 0x093C'i32),
    (0x0941'i32, 0x0948'i32),
    (0x094D'i32, 0x094D'i32),
    (0x0951'i32, 0x0957'i32),
    (0x0962'i32, 0x0963'i32),
    (0x0981'i32, 0x0981'i32),
    (0x09BC'i32, 0x09BC'i32),
    (0x09BE'i32, 0x09BE'i32),
    (0x09C1'i32, 0x09C4'i32),
    (0x09CD'i32, 0x09CD'i32),
    (0x09D7'i32, 0x09D7'i32),
    (0x09E2'i32, 0x09E3'i32),
    (0x09FE'i32, 0x09FE'i32),
    (0x0A01'i32, 0x0A02'i32),
    (0x0A3C'i32, 0x0A3C'i32),
    (0x0A41'i32, 0x0A42'i32),
    (0x0A47'i32, 0x0A48'i32),
    (0x0A4B'i32, 0x0A4D'i32),
    (0x0A51'i32, 0x0A51'i32),
    (0x0A70'i32, 0x0A71'i32),
    (0x0A75'i32, 0x0A75'i32),
    (0x0A81'i32, 0x0A82'i32),
    (0x0ABC'i32, 0x0ABC'i32),
    (0x0AC1'i32, 0x0AC5'i32),
    (0x0AC7'i32, 0x0AC8'i32),
    (0x0ACD'i32, 0x0ACD'i32),
    (0x0AE2'i32, 0x0AE3'i32),
    (0x0AFA'i32, 0x0AFF'i32),
    (0x0B01'i32, 0x0B01'i32),
    (0x0B3C'i32, 0x0B3C'i32),
    (0x0B3E'i32, 0x0B3F'i32),
    (0x0B41'i32, 0x0B44'i32),
    (0x0B4D'i32, 0x0B4D'i32),
    (0x0B55'i32, 0x0B57'i32),
    (0x0B62'i32, 0x0B63'i32),
    (0x0B82'i32, 0x0B82'i32),
    (0x0BBE'i32, 0x0BBE'i32),
    (0x0BC0'i32, 0x0BC0'i32),
    (0x0BCD'i32, 0x0BCD'i32),
    (0x0BD7'i32, 0x0BD7'i32),
    (0x0C00'i32, 0x0C00'i32),
    (0x0C04'i32, 0x0C04'i32),
    (0x0C3C'i32, 0x0C3C'i32),
    (0x0C3E'i32, 0x0C40'i32),
    (0x0C46'i32, 0x0C48'i32),
    (0x0C4A'i32, 0x0C4D'i32),
    (0x0C55'i32, 0x0C56'i32),
    (0x0C62'i32, 0x0C63'i32),
    (0x0C81'i32, 0x0C81'i32),
    (0x0CBC'i32, 0x0CBC'i32),
    (0x0CBF'i32, 0x0CC0'i32),
    (0x0CC2'i32, 0x0CC2'i32),
    (0x0CC6'i32, 0x0CC8'i32),
    (0x0CCA'i32, 0x0CCD'i32),
    (0x0CD5'i32, 0x0CD6'i32),
    (0x0CE2'i32, 0x0CE3'i32),
    (0x0D00'i32, 0x0D01'i32),
    (0x0D3B'i32, 0x0D3C'i32),
    (0x0D3E'i32, 0x0D3E'i32),
    (0x0D41'i32, 0x0D44'i32),
    (0x0D4D'i32, 0x0D4D'i32),
    (0x0D57'i32, 0x0D57'i32),
    (0x0D62'i32, 0x0D63'i32),
    (0x0D81'i32, 0x0D81'i32),
    (0x0DCA'i32, 0x0DCA'i32),
    (0x0DCF'i32, 0x0DCF'i32),
    (0x0DD2'i32, 0x0DD4'i32),
    (0x0DD6'i32, 0x0DD6'i32),
    (0x0DDF'i32, 0x0DDF'i32),
    (0x0E31'i32, 0x0E31'i32),
    (0x0E34'i32, 0x0E3A'i32),
    (0x0E47'i32, 0x0E4E'i32),
    (0x0EB1'i32, 0x0EB1'i32),
    (0x0EB4'i32, 0x0EBC'i32),
    (0x0EC8'i32, 0x0ECE'i32),
    (0x0F18'i32, 0x0F19'i32),
    (0x0F35'i32, 0x0F35'i32),
    (0x0F37'i32, 0x0F37'i32),
    (0x0F39'i32, 0x0F39'i32),
    (0x0F71'i32, 0x0F7E'i32),
    (0x0F80'i32, 0x0F84'i32),
    (0x0F86'i32, 0x0F87'i32),
    (0x0F8D'i32, 0x0F97'i32),
    (0x0F99'i32, 0x0FBC'i32),
    (0x0FC6'i32, 0x0FC6'i32),
    (0x102D'i32, 0x1030'i32),
    (0x1032'i32, 0x1037'i32),
    (0x1039'i32, 0x103A'i32),
    (0x103D'i32, 0x103E'i32),
    (0x1058'i32, 0x1059'i32),
    (0x105E'i32, 0x1060'i32),
    (0x1071'i32, 0x1074'i32),
    (0x1082'i32, 0x1082'i32),
    (0x1085'i32, 0x1086'i32),
    (0x108D'i32, 0x108D'i32),
    (0x109D'i32, 0x109D'i32),
    (0x135D'i32, 0x135F'i32),
    (0x1712'i32, 0x1715'i32),
    (0x1732'i32, 0x1734'i32),
    (0x1752'i32, 0x1753'i32),
    (0x1772'i32, 0x1773'i32),
    (0x17B4'i32, 0x17B5'i32),
    (0x17B7'i32, 0x17BD'i32),
    (0x17C6'i32, 0x17C6'i32),
    (0x17C9'i32, 0x17D3'i32),
    (0x17DD'i32, 0x17DD'i32),
    (0x180B'i32, 0x180D'i32),
    (0x180F'i32, 0x180F'i32),
    (0x1885'i32, 0x1886'i32),
    (0x18A9'i32, 0x18A9'i32),
    (0x1920'i32, 0x1922'i32),
    (0x1927'i32, 0x1928'i32),
    (0x1932'i32, 0x1932'i32),
    (0x1939'i32, 0x193B'i32),
    (0x1A17'i32, 0x1A18'i32),
    (0x1A1B'i32, 0x1A1B'i32),
    (0x1A56'i32, 0x1A56'i32),
    (0x1A58'i32, 0x1A5E'i32),
    (0x1A60'i32, 0x1A60'i32),
    (0x1A62'i32, 0x1A62'i32),
    (0x1A65'i32, 0x1A6C'i32),
    (0x1A73'i32, 0x1A7C'i32),
    (0x1A7F'i32, 0x1A7F'i32),
    (0x1AB0'i32, 0x1ADD'i32),
    (0x1AE0'i32, 0x1AEB'i32),
    (0x1B00'i32, 0x1B03'i32),
    (0x1B34'i32, 0x1B3D'i32),
    (0x1B42'i32, 0x1B44'i32),
    (0x1B6B'i32, 0x1B73'i32),
    (0x1B80'i32, 0x1B81'i32),
    (0x1BA2'i32, 0x1BA5'i32),
    (0x1BA8'i32, 0x1BAD'i32),
    (0x1BE6'i32, 0x1BE6'i32),
    (0x1BE8'i32, 0x1BE9'i32),
    (0x1BED'i32, 0x1BED'i32),
    (0x1BEF'i32, 0x1BF3'i32),
    (0x1C2C'i32, 0x1C33'i32),
    (0x1C36'i32, 0x1C37'i32),
    (0x1CD0'i32, 0x1CD2'i32),
    (0x1CD4'i32, 0x1CE0'i32),
    (0x1CE2'i32, 0x1CE8'i32),
    (0x1CED'i32, 0x1CED'i32),
    (0x1CF4'i32, 0x1CF4'i32),
    (0x1CF8'i32, 0x1CF9'i32),
    (0x1DC0'i32, 0x1DFF'i32),
    (0x200C'i32, 0x200C'i32),
    (0x20D0'i32, 0x20F0'i32),
    (0x2CEF'i32, 0x2CF1'i32),
    (0x2D7F'i32, 0x2D7F'i32),
    (0x2DE0'i32, 0x2DFF'i32),
    (0x302A'i32, 0x302F'i32),
    (0x3099'i32, 0x309A'i32),
    (0xA66F'i32, 0xA672'i32),
    (0xA674'i32, 0xA67D'i32),
    (0xA69E'i32, 0xA69F'i32),
    (0xA6F0'i32, 0xA6F1'i32),
    (0xA802'i32, 0xA802'i32),
    (0xA806'i32, 0xA806'i32),
    (0xA80B'i32, 0xA80B'i32),
    (0xA825'i32, 0xA826'i32),
    (0xA82C'i32, 0xA82C'i32),
    (0xA8C4'i32, 0xA8C5'i32),
    (0xA8E0'i32, 0xA8F1'i32),
    (0xA8FF'i32, 0xA8FF'i32),
    (0xA926'i32, 0xA92D'i32),
    (0xA947'i32, 0xA951'i32),
    (0xA953'i32, 0xA953'i32),
    (0xA980'i32, 0xA982'i32),
    (0xA9B3'i32, 0xA9B3'i32),
    (0xA9B6'i32, 0xA9B9'i32),
    (0xA9BC'i32, 0xA9BD'i32),
    (0xA9C0'i32, 0xA9C0'i32),
    (0xA9E5'i32, 0xA9E5'i32),
    (0xAA29'i32, 0xAA2E'i32),
    (0xAA31'i32, 0xAA32'i32),
    (0xAA35'i32, 0xAA36'i32),
    (0xAA43'i32, 0xAA43'i32),
    (0xAA4C'i32, 0xAA4C'i32),
    (0xAA7C'i32, 0xAA7C'i32),
    (0xAAB0'i32, 0xAAB0'i32),
    (0xAAB2'i32, 0xAAB4'i32),
    (0xAAB7'i32, 0xAAB8'i32),
    (0xAABE'i32, 0xAABF'i32),
    (0xAAC1'i32, 0xAAC1'i32),
    (0xAAEC'i32, 0xAAED'i32),
    (0xAAF6'i32, 0xAAF6'i32),
    (0xABE5'i32, 0xABE5'i32),
    (0xABE8'i32, 0xABE8'i32),
    (0xABED'i32, 0xABED'i32),
    (0xFB1E'i32, 0xFB1E'i32),
    (0xFE00'i32, 0xFE0F'i32),
    (0xFE20'i32, 0xFE2F'i32),
    (0xFF9E'i32, 0xFF9F'i32),
    (0x101FD'i32, 0x101FD'i32),
    (0x102E0'i32, 0x102E0'i32),
    (0x10376'i32, 0x1037A'i32),
    (0x10A01'i32, 0x10A03'i32),
    (0x10A05'i32, 0x10A06'i32),
    (0x10A0C'i32, 0x10A0F'i32),
    (0x10A38'i32, 0x10A3A'i32),
    (0x10A3F'i32, 0x10A3F'i32),
    (0x10AE5'i32, 0x10AE6'i32),
    (0x10D24'i32, 0x10D27'i32),
    (0x10D69'i32, 0x10D6D'i32),
    (0x10EAB'i32, 0x10EAC'i32),
    (0x10EFA'i32, 0x10EFF'i32),
    (0x10F46'i32, 0x10F50'i32),
    (0x10F82'i32, 0x10F85'i32),
    (0x11001'i32, 0x11001'i32),
    (0x11038'i32, 0x11046'i32),
    (0x11070'i32, 0x11070'i32),
    (0x11073'i32, 0x11074'i32),
    (0x1107F'i32, 0x11081'i32),
    (0x110B3'i32, 0x110B6'i32),
    (0x110B9'i32, 0x110BA'i32),
    (0x110C2'i32, 0x110C2'i32),
    (0x11100'i32, 0x11102'i32),
    (0x11127'i32, 0x1112B'i32),
    (0x1112D'i32, 0x11134'i32),
    (0x11173'i32, 0x11173'i32),
    (0x11180'i32, 0x11181'i32),
    (0x111B6'i32, 0x111BE'i32),
    (0x111C0'i32, 0x111C0'i32),
    (0x111C9'i32, 0x111CC'i32),
    (0x111CF'i32, 0x111CF'i32),
    (0x1122F'i32, 0x11231'i32),
    (0x11234'i32, 0x11237'i32),
    (0x1123E'i32, 0x1123E'i32),
    (0x11241'i32, 0x11241'i32),
    (0x112DF'i32, 0x112DF'i32),
    (0x112E3'i32, 0x112EA'i32),
    (0x11300'i32, 0x11301'i32),
    (0x1133B'i32, 0x1133C'i32),
    (0x1133E'i32, 0x1133E'i32),
    (0x11340'i32, 0x11340'i32),
    (0x1134D'i32, 0x1134D'i32),
    (0x11357'i32, 0x11357'i32),
    (0x11366'i32, 0x1136C'i32),
    (0x11370'i32, 0x11374'i32),
    (0x113B8'i32, 0x113B8'i32),
    (0x113BB'i32, 0x113C0'i32),
    (0x113C2'i32, 0x113C2'i32),
    (0x113C5'i32, 0x113C5'i32),
    (0x113C7'i32, 0x113C9'i32),
    (0x113CE'i32, 0x113D0'i32),
    (0x113D2'i32, 0x113D2'i32),
    (0x113E1'i32, 0x113E2'i32),
    (0x11438'i32, 0x1143F'i32),
    (0x11442'i32, 0x11444'i32),
    (0x11446'i32, 0x11446'i32),
    (0x1145E'i32, 0x1145E'i32),
    (0x114B0'i32, 0x114B0'i32),
    (0x114B3'i32, 0x114B8'i32),
    (0x114BA'i32, 0x114BA'i32),
    (0x114BD'i32, 0x114BD'i32),
    (0x114BF'i32, 0x114C0'i32),
    (0x114C2'i32, 0x114C3'i32),
    (0x115AF'i32, 0x115AF'i32),
    (0x115B2'i32, 0x115B5'i32),
    (0x115BC'i32, 0x115BD'i32),
    (0x115BF'i32, 0x115C0'i32),
    (0x115DC'i32, 0x115DD'i32),
    (0x11633'i32, 0x1163A'i32),
    (0x1163D'i32, 0x1163D'i32),
    (0x1163F'i32, 0x11640'i32),
    (0x116AB'i32, 0x116AB'i32),
    (0x116AD'i32, 0x116AD'i32),
    (0x116B0'i32, 0x116B7'i32),
    (0x1171D'i32, 0x1171D'i32),
    (0x1171F'i32, 0x1171F'i32),
    (0x11722'i32, 0x11725'i32),
    (0x11727'i32, 0x1172B'i32),
    (0x1182F'i32, 0x11837'i32),
    (0x11839'i32, 0x1183A'i32),
    (0x11930'i32, 0x11930'i32),
    (0x1193B'i32, 0x1193E'i32),
    (0x11943'i32, 0x11943'i32),
    (0x119D4'i32, 0x119D7'i32),
    (0x119DA'i32, 0x119DB'i32),
    (0x119E0'i32, 0x119E0'i32),
    (0x11A01'i32, 0x11A0A'i32),
    (0x11A33'i32, 0x11A38'i32),
    (0x11A3B'i32, 0x11A3E'i32),
    (0x11A47'i32, 0x11A47'i32),
    (0x11A51'i32, 0x11A56'i32),
    (0x11A59'i32, 0x11A5B'i32),
    (0x11A8A'i32, 0x11A96'i32),
    (0x11A98'i32, 0x11A99'i32),
    (0x11B60'i32, 0x11B60'i32),
    (0x11B62'i32, 0x11B64'i32),
    (0x11B66'i32, 0x11B66'i32),
    (0x11C30'i32, 0x11C36'i32),
    (0x11C38'i32, 0x11C3D'i32),
    (0x11C3F'i32, 0x11C3F'i32),
    (0x11C92'i32, 0x11CA7'i32),
    (0x11CAA'i32, 0x11CB0'i32),
    (0x11CB2'i32, 0x11CB3'i32),
    (0x11CB5'i32, 0x11CB6'i32),
    (0x11D31'i32, 0x11D36'i32),
    (0x11D3A'i32, 0x11D3A'i32),
    (0x11D3C'i32, 0x11D3D'i32),
    (0x11D3F'i32, 0x11D45'i32),
    (0x11D47'i32, 0x11D47'i32),
    (0x11D90'i32, 0x11D91'i32),
    (0x11D95'i32, 0x11D95'i32),
    (0x11D97'i32, 0x11D97'i32),
    (0x11EF3'i32, 0x11EF4'i32),
    (0x11F00'i32, 0x11F01'i32),
    (0x11F36'i32, 0x11F3A'i32),
    (0x11F40'i32, 0x11F42'i32),
    (0x11F5A'i32, 0x11F5A'i32),
    (0x13440'i32, 0x13440'i32),
    (0x13447'i32, 0x13455'i32),
    (0x1611E'i32, 0x16129'i32),
    (0x1612D'i32, 0x1612F'i32),
    (0x16AF0'i32, 0x16AF4'i32),
    (0x16B30'i32, 0x16B36'i32),
    (0x16F4F'i32, 0x16F4F'i32),
    (0x16F8F'i32, 0x16F92'i32),
    (0x16FE4'i32, 0x16FE4'i32),
    (0x16FF0'i32, 0x16FF1'i32),
    (0x1BC9D'i32, 0x1BC9E'i32),
    (0x1CF00'i32, 0x1CF2D'i32),
    (0x1CF30'i32, 0x1CF46'i32),
    (0x1D165'i32, 0x1D169'i32),
    (0x1D16D'i32, 0x1D172'i32),
    (0x1D17B'i32, 0x1D182'i32),
    (0x1D185'i32, 0x1D18B'i32),
    (0x1D1AA'i32, 0x1D1AD'i32),
    (0x1D242'i32, 0x1D244'i32),
    (0x1DA00'i32, 0x1DA36'i32),
    (0x1DA3B'i32, 0x1DA6C'i32),
    (0x1DA75'i32, 0x1DA75'i32),
    (0x1DA84'i32, 0x1DA84'i32),
    (0x1DA9B'i32, 0x1DA9F'i32),
    (0x1DAA1'i32, 0x1DAAF'i32),
    (0x1E000'i32, 0x1E006'i32),
    (0x1E008'i32, 0x1E018'i32),
    (0x1E01B'i32, 0x1E021'i32),
    (0x1E023'i32, 0x1E024'i32),
    (0x1E026'i32, 0x1E02A'i32),
    (0x1E08F'i32, 0x1E08F'i32),
    (0x1E130'i32, 0x1E136'i32),
    (0x1E2AE'i32, 0x1E2AE'i32),
    (0x1E2EC'i32, 0x1E2EF'i32),
    (0x1E4EC'i32, 0x1E4EF'i32),
    (0x1E5EE'i32, 0x1E5EF'i32),
    (0x1E6E3'i32, 0x1E6E3'i32),
    (0x1E6E6'i32, 0x1E6E6'i32),
    (0x1E6EE'i32, 0x1E6EF'i32),
    (0x1E6F5'i32, 0x1E6F5'i32),
    (0x1E8D0'i32, 0x1E8D6'i32),
    (0x1E944'i32, 0x1E94A'i32),
    (0x1F3FB'i32, 0x1F3FF'i32),
    (0xE0020'i32, 0xE007F'i32),
    (0xE0100'i32, 0xE01EF'i32),
  ]

  # Grapheme_Cluster_Break=L/V/T (GraphemeBreakProperty.txt): the conjoining
  # jamo blocks.  Wider than the composition ranges: GCB=V starts at U+1160
  # (the jungseong filler) and GCB=T runs to U+11FF.
  HangulLRanges: array[2, (int32, int32)] =
    [(0x1100'i32, 0x115F'i32), (0xA960'i32, 0xA97C'i32)]

  HangulVRanges: array[4, (int32, int32)] = [
    (0x1160'i32, 0x11A7'i32),
    (0xD7B0'i32, 0xD7C6'i32),
    (0x16D63'i32, 0x16D63'i32),
    (0x16D67'i32, 0x16D6A'i32),
  ]

  HangulTRanges: array[2, (int32, int32)] =
    [(0x11A8'i32, 0x11FF'i32), (0xD7CB'i32, 0xD7FB'i32)]

  # Grapheme_Cluster_Break=Prepend (GraphemeBreakProperty.txt)
  PrependRanges: array[15, (int32, int32)] = [
    (0x0600'i32, 0x0605'i32),
    (0x06DD'i32, 0x06DD'i32),
    (0x070F'i32, 0x070F'i32),
    (0x0890'i32, 0x0891'i32),
    (0x08E2'i32, 0x08E2'i32),
    (0x0D4E'i32, 0x0D4E'i32),
    (0x110BD'i32, 0x110BD'i32),
    (0x110CD'i32, 0x110CD'i32),
    (0x111C2'i32, 0x111C3'i32),
    (0x113D1'i32, 0x113D1'i32),
    (0x1193F'i32, 0x1193F'i32),
    (0x11941'i32, 0x11941'i32),
    (0x11A84'i32, 0x11A89'i32),
    (0x11D46'i32, 0x11D46'i32),
    (0x11F02'i32, 0x11F02'i32),
  ]

  # Grapheme_Cluster_Break=SpacingMark (GraphemeBreakProperty.txt): most Mc
  # characters that are not Grapheme_Extend, plus U+0E33 and U+0EB3 (Lo).
  SpacingMarkRanges: array[158, (int32, int32)] = [
    (0x0903'i32, 0x0903'i32),
    (0x093B'i32, 0x093B'i32),
    (0x093E'i32, 0x0940'i32),
    (0x0949'i32, 0x094C'i32),
    (0x094E'i32, 0x094F'i32),
    (0x0982'i32, 0x0983'i32),
    (0x09BF'i32, 0x09C0'i32),
    (0x09C7'i32, 0x09C8'i32),
    (0x09CB'i32, 0x09CC'i32),
    (0x0A03'i32, 0x0A03'i32),
    (0x0A3E'i32, 0x0A40'i32),
    (0x0A83'i32, 0x0A83'i32),
    (0x0ABE'i32, 0x0AC0'i32),
    (0x0AC9'i32, 0x0AC9'i32),
    (0x0ACB'i32, 0x0ACC'i32),
    (0x0B02'i32, 0x0B03'i32),
    (0x0B40'i32, 0x0B40'i32),
    (0x0B47'i32, 0x0B48'i32),
    (0x0B4B'i32, 0x0B4C'i32),
    (0x0BBF'i32, 0x0BBF'i32),
    (0x0BC1'i32, 0x0BC2'i32),
    (0x0BC6'i32, 0x0BC8'i32),
    (0x0BCA'i32, 0x0BCC'i32),
    (0x0C01'i32, 0x0C03'i32),
    (0x0C41'i32, 0x0C44'i32),
    (0x0C82'i32, 0x0C83'i32),
    (0x0CBE'i32, 0x0CBE'i32),
    (0x0CC1'i32, 0x0CC1'i32),
    (0x0CC3'i32, 0x0CC4'i32),
    (0x0CF3'i32, 0x0CF3'i32),
    (0x0D02'i32, 0x0D03'i32),
    (0x0D3F'i32, 0x0D40'i32),
    (0x0D46'i32, 0x0D48'i32),
    (0x0D4A'i32, 0x0D4C'i32),
    (0x0D82'i32, 0x0D83'i32),
    (0x0DD0'i32, 0x0DD1'i32),
    (0x0DD8'i32, 0x0DDE'i32),
    (0x0DF2'i32, 0x0DF3'i32),
    (0x0E33'i32, 0x0E33'i32),
    (0x0EB3'i32, 0x0EB3'i32),
    (0x0F3E'i32, 0x0F3F'i32),
    (0x0F7F'i32, 0x0F7F'i32),
    (0x1031'i32, 0x1031'i32),
    (0x103B'i32, 0x103C'i32),
    (0x1056'i32, 0x1057'i32),
    (0x1084'i32, 0x1084'i32),
    (0x17B6'i32, 0x17B6'i32),
    (0x17BE'i32, 0x17C5'i32),
    (0x17C7'i32, 0x17C8'i32),
    (0x1923'i32, 0x1926'i32),
    (0x1929'i32, 0x192B'i32),
    (0x1930'i32, 0x1931'i32),
    (0x1933'i32, 0x1938'i32),
    (0x1A19'i32, 0x1A1A'i32),
    (0x1A55'i32, 0x1A55'i32),
    (0x1A57'i32, 0x1A57'i32),
    (0x1A6D'i32, 0x1A72'i32),
    (0x1B04'i32, 0x1B04'i32),
    (0x1B3E'i32, 0x1B41'i32),
    (0x1B82'i32, 0x1B82'i32),
    (0x1BA1'i32, 0x1BA1'i32),
    (0x1BA6'i32, 0x1BA7'i32),
    (0x1BE7'i32, 0x1BE7'i32),
    (0x1BEA'i32, 0x1BEC'i32),
    (0x1BEE'i32, 0x1BEE'i32),
    (0x1C24'i32, 0x1C2B'i32),
    (0x1C34'i32, 0x1C35'i32),
    (0x1CE1'i32, 0x1CE1'i32),
    (0x1CF7'i32, 0x1CF7'i32),
    (0xA823'i32, 0xA824'i32),
    (0xA827'i32, 0xA827'i32),
    (0xA880'i32, 0xA881'i32),
    (0xA8B4'i32, 0xA8C3'i32),
    (0xA952'i32, 0xA952'i32),
    (0xA983'i32, 0xA983'i32),
    (0xA9B4'i32, 0xA9B5'i32),
    (0xA9BA'i32, 0xA9BB'i32),
    (0xA9BE'i32, 0xA9BF'i32),
    (0xAA2F'i32, 0xAA30'i32),
    (0xAA33'i32, 0xAA34'i32),
    (0xAA4D'i32, 0xAA4D'i32),
    (0xAAEB'i32, 0xAAEB'i32),
    (0xAAEE'i32, 0xAAEF'i32),
    (0xAAF5'i32, 0xAAF5'i32),
    (0xABE3'i32, 0xABE4'i32),
    (0xABE6'i32, 0xABE7'i32),
    (0xABE9'i32, 0xABEA'i32),
    (0xABEC'i32, 0xABEC'i32),
    (0x11000'i32, 0x11000'i32),
    (0x11002'i32, 0x11002'i32),
    (0x11082'i32, 0x11082'i32),
    (0x110B0'i32, 0x110B2'i32),
    (0x110B7'i32, 0x110B8'i32),
    (0x1112C'i32, 0x1112C'i32),
    (0x11145'i32, 0x11146'i32),
    (0x11182'i32, 0x11182'i32),
    (0x111B3'i32, 0x111B5'i32),
    (0x111BF'i32, 0x111BF'i32),
    (0x111CE'i32, 0x111CE'i32),
    (0x1122C'i32, 0x1122E'i32),
    (0x11232'i32, 0x11233'i32),
    (0x112E0'i32, 0x112E2'i32),
    (0x11302'i32, 0x11303'i32),
    (0x1133F'i32, 0x1133F'i32),
    (0x11341'i32, 0x11344'i32),
    (0x11347'i32, 0x11348'i32),
    (0x1134B'i32, 0x1134C'i32),
    (0x11362'i32, 0x11363'i32),
    (0x113B9'i32, 0x113BA'i32),
    (0x113CA'i32, 0x113CA'i32),
    (0x113CC'i32, 0x113CD'i32),
    (0x11435'i32, 0x11437'i32),
    (0x11440'i32, 0x11441'i32),
    (0x11445'i32, 0x11445'i32),
    (0x114B1'i32, 0x114B2'i32),
    (0x114B9'i32, 0x114B9'i32),
    (0x114BB'i32, 0x114BC'i32),
    (0x114BE'i32, 0x114BE'i32),
    (0x114C1'i32, 0x114C1'i32),
    (0x115B0'i32, 0x115B1'i32),
    (0x115B8'i32, 0x115BB'i32),
    (0x115BE'i32, 0x115BE'i32),
    (0x11630'i32, 0x11632'i32),
    (0x1163B'i32, 0x1163C'i32),
    (0x1163E'i32, 0x1163E'i32),
    (0x116AC'i32, 0x116AC'i32),
    (0x116AE'i32, 0x116AF'i32),
    (0x1171E'i32, 0x1171E'i32),
    (0x11726'i32, 0x11726'i32),
    (0x1182C'i32, 0x1182E'i32),
    (0x11838'i32, 0x11838'i32),
    (0x11931'i32, 0x11935'i32),
    (0x11937'i32, 0x11938'i32),
    (0x11940'i32, 0x11940'i32),
    (0x11942'i32, 0x11942'i32),
    (0x119D1'i32, 0x119D3'i32),
    (0x119DC'i32, 0x119DF'i32),
    (0x119E4'i32, 0x119E4'i32),
    (0x11A39'i32, 0x11A39'i32),
    (0x11A57'i32, 0x11A58'i32),
    (0x11A97'i32, 0x11A97'i32),
    (0x11B61'i32, 0x11B61'i32),
    (0x11B65'i32, 0x11B65'i32),
    (0x11B67'i32, 0x11B67'i32),
    (0x11C2F'i32, 0x11C2F'i32),
    (0x11C3E'i32, 0x11C3E'i32),
    (0x11CA9'i32, 0x11CA9'i32),
    (0x11CB1'i32, 0x11CB1'i32),
    (0x11CB4'i32, 0x11CB4'i32),
    (0x11D8A'i32, 0x11D8E'i32),
    (0x11D93'i32, 0x11D94'i32),
    (0x11D96'i32, 0x11D96'i32),
    (0x11EF5'i32, 0x11EF6'i32),
    (0x11F03'i32, 0x11F03'i32),
    (0x11F34'i32, 0x11F35'i32),
    (0x11F3E'i32, 0x11F3F'i32),
    (0x1612A'i32, 0x1612C'i32),
    (0x16F51'i32, 0x16F87'i32),
  ]

const MaxCodePoint = 0x0010FFFF'i32

proc isCodePoint*(r: Rune): bool {.inline.} =
  ## Whether ``r`` is a code point at all.  The subject is never validated, so
  ## ``fastRuneAt`` can decode a malformed sequence far above U+10FFFF, which
  ## every ``unicodedb`` lookup rejects with ``doAssert``.  Such a value is
  ## treated as unassigned and folds to itself.
  int32(r) >= 0'i32 and int32(r) <= MaxCodePoint

proc unicodeCategory(r: Rune): UnicodeCategory {.inline.} =
  if r.isCodePoint:
    properties.unicodeCategory(r)
  else:
    ctgCn

proc unicodeTypes(r: Rune): int {.inline.} =
  if r.isCodePoint:
    udbTypes.unicodeTypes(r)
  else:
    0

proc wordBreakProp(r: Rune): SgWord {.inline.} =
  if r.isCodePoint:
    segmentation.wordBreakProp(r)
  else:
    sgwOther

proc simpleCaseFold(r: Rune): Rune {.inline.} =
  if r.isCodePoint:
    casing.simpleCaseFold(r)
  else:
    r

iterator caseFoldVariants*(r: Rune): Rune =
  ## Every code point sharing ``r``'s simple case fold, ``r`` included.
  if r.isCodePoint:
    for variant in resolveCaseFold(r):
      yield variant
  else:
    yield r

proc inRangeTable*(cp: int32, table: openArray[(int32, int32)]): bool =
  ## Binary search a sorted table of (start, end) ranges.
  var lo = 0
  var hi = table.len - 1
  while lo <= hi:
    let mid = (lo + hi) div 2
    let (s, e) = table[mid]
    if cp < s:
      hi = mid - 1
    elif cp > e:
      lo = mid + 1
    else:
      return true
  return false

proc isOtherAlphabetic(r: Rune): bool {.inline.} =
  let cp = int32(r)
  # The table starts at U+0345, so everything below it (all of ASCII) is out.
  if cp < OtherAlphabeticRanges[0][0]:
    return false
  inRangeTable(cp, OtherAlphabeticRanges)

proc isAlphaChar*(r: Rune, cat: UnicodeCategory): bool {.inline.} =
  ## Oniguruma/POSIX Alpha: Unicode Alphabetic = L ∪ Nl ∪ Other_Alphabetic.
  ## Takes an already-resolved category to avoid a second lookup.
  cat in ctgL or cat == ctgNl or isOtherAlphabetic(r)

proc isAlphaChar*(r: Rune): bool {.inline.} =
  isAlphaChar(r, unicodeCategory(r))

proc isWordChar*(r: Rune, asciiOnly: bool, latin1Digits = true): bool {.inline.} =
  ## \w / Word: Alpha ∪ M ∪ Nd ∪ Pc ∪ six Latin-1 No digits (² ³ ¹ ¼ ½ ¾).
  ##
  ## Those six come from Oniguruma's ISO-8859-1 ctype override, which applies
  ## to a bare ``\w`` / ``\p{Word}`` only; ``[[:word:]]`` and any spelling
  ## inside ``[...]`` use the raw ``CR_Word`` ranges (``latin1Digits = false``).
  let c = int32(r)
  if c >= 0 and c < 128:
    return asciiHas(c, acWord)
  if asciiOnly:
    return false
  if latin1Digits and c < 0x0100 and (
    c == 0x00B2 or c == 0x00B3 or c == 0x00B9 or c == 0x00BC or c == 0x00BD or
    c == 0x00BE
  ):
    return true
  let cat = unicodeCategory(r)
  # Same set as Alpha ∪ M ∪ Nd ∪ Pc, but ordered so the Other_Alphabetic
  # range search stays the last resort instead of running for every M/Nd/Pc.
  cat in ctgL or cat in ctgM or cat == ctgNd or cat == ctgPc or cat == ctgNl or
    isOtherAlphabetic(r)

proc isDigitChar*(r: Rune, asciiOnly: bool): bool {.inline.} =
  ## \d: Decimal digit
  let c = int32(r)
  if c >= 0 and c < 128:
    return asciiHas(c, acDigit)
  if asciiOnly:
    return false
  unicodeCategory(r) == ctgNd

proc isSpaceChar*(r: Rune, asciiOnly: bool): bool {.inline.} =
  ## \s: Whitespace
  let c = int32(r)
  if c >= 0 and c < 128:
    return asciiHas(c, acSpace)
  if asciiOnly:
    return false
  let cat = unicodeCategory(r)
  cat in ctgZ or c == 0x85

proc isHexDigitChar*(r: Rune): bool {.inline.} =
  ## \h: Hex digit (always ASCII)
  let c = int32(r)
  asciiHas(c, acXdigit)

proc simpleFold*(r: Rune): Rune =
  ## Simple case fold for case-insensitive matching
  simpleCaseFold(r)

proc getMultiCharFold*(r: Rune): RuneBuf =
  ## The multi-character case fold expansion of ``r``, or ``len == 0`` when it
  ## has none.  Read straight out of [MultiCharFolds].
  if not hasMultiCharFold(r):
    return RuneBuf(runes: [Rune(0), Rune(0), Rune(0)], len: 0)
  let cp = int32(r)
  for f in MultiCharFolds:
    if f.source == cp:
      return RuneBuf(
        runes: [Rune(f.expansion[0]), Rune(f.expansion[1]), Rune(f.expansion[2])],
        len: f.len,
      )
  RuneBuf(runes: [Rune(0), Rune(0), Rune(0)], len: 0)

proc posixAsciiOnly*(cls: PosixClassName, flags: RegexFlags): bool =
  ## Check if POSIX class should use ASCII-only matching based on flags.
  ## (?P) implies all of them; (?W)/(?D)/(?S) only add the word/digit/space
  ## ctypes on top of it.
  if rfAsciiPosix in flags:
    return true
  case cls
  of pcWord:
    rfAsciiWord in flags
  of pcDigit:
    rfAsciiDigit in flags
  of pcSpace:
    rfAsciiSpace in flags
  else:
    # Oniguruma's ONIG_OPTION_WORD_IS_ASCII covers the WORD ctype only, so
    # (?W) must not narrow [[:alpha:]] / [[:alnum:]]; only (?P) does.
    false

proc matchPosixClass*(r: Rune, cls: PosixClassName, asciiOnly: bool): bool =
  let c = int32(r)
  if c >= 0 and c < 128:
    # ASCII: the table already agrees with both readings of every class.
    return
      case cls
      of pcAlnum:
        asciiHas(c, acAlnum)
      of pcAlpha:
        asciiHas(c, acAlpha)
      of pcAscii:
        true
      of pcBlank:
        asciiHas(c, acBlank)
      of pcCntrl:
        asciiHas(c, acCntrl)
      of pcDigit:
        asciiHas(c, acDigit)
      of pcGraph:
        asciiHas(c, acGraph)
      of pcLower:
        asciiHas(c, acLower)
      of pcPrint:
        asciiHas(c, acPrint)
      of pcPunct:
        asciiHas(c, acPunct)
      of pcSpace:
        asciiHas(c, acSpace)
      of pcUpper:
        asciiHas(c, acUpper)
      of pcXdigit:
        asciiHas(c, acXdigit)
      of pcWord:
        asciiHas(c, acWord)
  case cls
  of pcAlnum:
    if asciiOnly:
      (c >= ord('a') and c <= ord('z')) or (c >= ord('A') and c <= ord('Z')) or
        (c >= ord('0') and c <= ord('9'))
    else:
      # Alpha ∪ Nd
      let cat = unicodeCategory(r)
      isAlphaChar(r, cat) or cat == ctgNd
  of pcAlpha:
    if asciiOnly:
      (c >= ord('a') and c <= ord('z')) or (c >= ord('A') and c <= ord('Z'))
    else:
      isAlphaChar(r)
  of pcAscii:
    c >= 0 and c <= 127
  of pcBlank:
    if asciiOnly:
      c == 0x20 or c == 0x09
    else:
      # Zs ∪ {U+0009}
      c == 0x09 or unicodeCategory(r) == ctgZs
  of pcCntrl:
    if asciiOnly:
      (c >= 0 and c < 0x20) or c == 0x7F
    else:
      unicodeCategory(r) == ctgCc
  of pcDigit:
    if asciiOnly:
      c >= ord('0') and c <= ord('9')
    else:
      unicodeCategory(r) == ctgNd
  of pcGraph:
    if asciiOnly:
      c > 0x20 and c < 0x7F
    else:
      # category ∉ (Z + Cc + Cs + Cn); Cf and Co are graph.
      let cat = unicodeCategory(r)
      not (cat in (ctgZ + ctgCc + ctgCs + ctgCn))
  of pcLower:
    if asciiOnly:
      c >= ord('a') and c <= ord('z')
    else:
      # Same derived-property set as \p{Lower}: Ll plus Other_Lowercase.
      utmLowercase in unicodeTypes(r)
  of pcPrint:
    if asciiOnly:
      c >= 0x20 and c < 0x7F
    else:
      # category ∉ (Cc + Cs + Cn + Zl + Zp); Zs and Cf are print.
      let cat = unicodeCategory(r)
      not (cat in (ctgCc + ctgCs + ctgCn + ctgZl + ctgZp))
  of pcPunct:
    if asciiOnly:
      (c >= ord('!') and c <= ord('/')) or (c >= ord(':') and c <= ord('@')) or
        (c >= ord('[') and c <= ord('`')) or (c >= ord('{') and c <= ord('~'))
    else:
      # Oniguruma XPosixPunct = P ∪ S (marks, letters, numbers and the
      # separator/other categories are all excluded).
      let cat = unicodeCategory(r)
      not (cat in ctgL or cat in ctgN or cat in ctgZ or cat in ctgC or cat in ctgM)
  of pcSpace:
    isSpaceChar(r, asciiOnly)
  of pcUpper:
    if asciiOnly:
      c >= ord('A') and c <= ord('Z')
    else:
      # Same derived-property set as \p{Upper}: Lu plus Other_Uppercase.
      utmUppercase in unicodeTypes(r)
  of pcXdigit:
    isHexDigitChar(r)
  of pcWord:
    isWordChar(r, asciiOnly, latin1Digits = false)

proc resolveScriptId(name: string): int32 =
  ## Map a lower-cased script name to its ``UnicodeScript`` value, or -1.
  case name
  of "common":
    int32(sptCommon)
  of "latin":
    int32(sptLatin)
  of "greek":
    int32(sptGreek)
  of "cyrillic":
    int32(sptCyrillic)
  of "armenian":
    int32(sptArmenian)
  of "hebrew":
    int32(sptHebrew)
  of "arabic":
    int32(sptArabic)
  of "han":
    int32(sptHan)
  of "hiragana":
    int32(sptHiragana)
  of "katakana":
    int32(sptKatakana)
  of "hangul":
    int32(sptHangul)
  of "thai":
    int32(sptThai)
  of "devanagari":
    int32(sptDevanagari)
  of "bengali":
    int32(sptBengali)
  of "tamil":
    int32(sptTamil)
  of "georgian":
    int32(sptGeorgian)
  of "ethiopic":
    int32(sptEthiopic)
  of "tibetan":
    int32(sptTibetan)
  of "myanmar":
    int32(sptMyanmar)
  of "bopomofo":
    int32(sptBopomofo)
  of "inherited":
    int32(sptInherited)
  of "coptic":
    int32(sptCoptic)
  of "syriac":
    int32(sptSyriac)
  of "khmer":
    int32(sptKhmer)
  of "mongolian":
    int32(sptMongolian)
  else:
    -1'i32

proc catProp(bits: UnicodeCategorySet): UniProp =
  UniProp(kind: upCategory, catBits: int32(bits))

proc catProp(cat: UnicodeCategory): UniProp =
  UniProp(kind: upCategory, catBits: int32(cat))

proc typeProp(mask: UnicodeTypeMask): UniProp =
  UniProp(kind: upTypeMask, typeBits: int32(mask))

proc posixProp(cls: PosixClassName): UniProp =
  UniProp(kind: upPosix, posixCls: cls)

proc resolveBlock(name: string): UniProp =
  ## Resolve an ``In<Block>`` name to an index into ``blockRanges``.
  let query = name[2 ..^ 1].replace(" ", "").replace("-", "").replace("_", "")
  for i, bn in blockNames.pairs:
    let normalBn = bn.toLowerAscii().replace(" ", "").replace("-", "").replace("_", "")
    if normalBn == query:
      return UniProp(kind: upBlock, blockIdx: int32(i))
  UniProp(kind: upNever)

proc resolveBlockOrScript(name: string): UniProp =
  ## Resolve a name that is neither a category nor a known alias.  Blocks take
  ## the "In" prefix and win the lookup, but an unmatched "In" name falls
  ## through: script names may start with "in" too (Inherited).
  if name.len > 2 and name.startsWith("in"):
    result = resolveBlock(name)
    if result.kind != upNever:
      return
  let sid = resolveScriptId(name)
  if sid >= 0:
    result = UniProp(kind: upScript, scriptId: sid)
  else:
    result = UniProp(kind: upNever)

proc resolvePropBody(name: string): UniProp =
  ## Resolve the flag-independent half of a ``\p{...}`` name.
  case name
  # Single-letter general categories
  of "l", "letter":
    catProp(ctgL)
  of "m", "mark":
    catProp(ctgM)
  of "n", "number":
    catProp(ctgN)
  of "p", "punct", "punctuation":
    catProp(ctgP)
  of "s", "symbol":
    catProp(ctgS)
  of "z", "separator":
    catProp(ctgZ)
  of "c", "other":
    catProp(ctgC)
  # Two-letter subcategories
  of "lu", "uppercase_letter":
    catProp(ctgLu)
  of "ll", "lowercase_letter":
    catProp(ctgLl)
  of "lt", "titlecase_letter":
    catProp(ctgLt)
  of "lm", "modifier_letter":
    catProp(ctgLm)
  of "lo", "other_letter":
    catProp(ctgLo)
  of "mn", "nonspacing_mark":
    catProp(ctgMn)
  of "mc", "spacing_mark":
    catProp(ctgMc)
  of "me", "enclosing_mark":
    catProp(ctgMe)
  of "nd", "decimal_number":
    catProp(ctgNd)
  of "nl", "letter_number":
    catProp(ctgNl)
  of "no", "other_number":
    catProp(ctgNo)
  of "pc", "connector_punctuation":
    catProp(ctgPc)
  of "pd", "dash_punctuation":
    catProp(ctgPd)
  of "ps", "open_punctuation":
    catProp(ctgPs)
  of "pe", "close_punctuation":
    catProp(ctgPe)
  of "pi", "initial_punctuation":
    catProp(ctgPi)
  of "pf", "final_punctuation":
    catProp(ctgPf)
  of "po", "other_punctuation":
    catProp(ctgPo)
  of "sm", "math_symbol":
    catProp(ctgSm)
  of "sc", "currency_symbol":
    catProp(ctgSc)
  of "sk", "modifier_symbol":
    catProp(ctgSk)
  of "so", "other_symbol":
    catProp(ctgSo)
  of "zs", "space_separator":
    catProp(ctgZs)
  of "zl", "line_separator":
    catProp(ctgZl)
  of "zp", "paragraph_separator":
    catProp(ctgZp)
  of "cc", "control":
    catProp(ctgCc)
  of "cf", "format":
    catProp(ctgCf)
  of "cs", "surrogate":
    catProp(ctgCs)
  of "co", "private_use":
    catProp(ctgCo)
  of "cn", "unassigned":
    catProp(ctgCn)
  # Common property aliases
  of "any":
    UniProp(kind: upAlways)
  of "ascii":
    UniProp(kind: upAscii)
  of "print":
    posixProp(pcPrint)
  of "graph":
    posixProp(pcGraph)
  of "alpha":
    # Same set as [[:alpha:]] / \p{PosixAlpha}: L ∪ Nl ∪ Other_Alphabetic.
    posixProp(pcAlpha)
  of "alnum":
    posixProp(pcAlnum)
  of "upper":
    # Derived Uppercase, not the Lu category, as in Oniguruma: Other_Uppercase
    # code points such as U+2160 ROMAN NUMERAL ONE match too.  Same for lower.
    typeProp(utmUppercase)
  of "lower":
    typeProp(utmLowercase)
  of "digit":
    catProp(ctgNd)
  of "space", "white_space":
    posixProp(pcSpace)
  of "word":
    UniProp(kind: upWord)
  of "blank":
    posixProp(pcBlank)
  of "cntrl":
    catProp(ctgCc)
  of "xdigit":
    posixProp(pcXdigit)
  of "posixpunct":
    posixProp(pcPunct)
  of "posixalnum":
    posixProp(pcAlnum)
  of "posixalpha":
    posixProp(pcAlpha)
  of "posixblank":
    posixProp(pcBlank)
  of "posixcntrl":
    posixProp(pcCntrl)
  of "posixdigit":
    posixProp(pcDigit)
  of "posixgraph":
    posixProp(pcGraph)
  of "posixlower":
    posixProp(pcLower)
  of "posixprint":
    posixProp(pcPrint)
  of "posixspace":
    posixProp(pcSpace)
  of "posixupper":
    posixProp(pcUpper)
  of "posixxdigit":
    posixProp(pcXdigit)
  of "posixword":
    posixProp(pcWord)
  # Emoji binary properties (emoji-data.txt)
  of "emoji":
    UniProp(kind: upEmoji)
  of "extended_pictographic", "extpict":
    UniProp(kind: upExtPict)
  else:
    resolveBlockOrScript(name)

proc resolveUnicodeProp*(propName: string, inClass = false): UniProp =
  ## Resolve a ``\p{...}`` name once, at compile time, so that matching never
  ## has to lower-case or compare strings.
  ##
  ## ``inClass`` marks a use inside ``[...]``, where Oniguruma expands the
  ## property to its raw ranges: ``[\p{Word}]`` drops the Latin-1 extras.
  let name = propName.toLowerAscii()
  result = resolvePropBody(name)
  if inClass and result.kind == upWord:
    result = posixProp(pcWord)
  # (?W)/(?D)/(?S) and the blanket (?P) restrict some properties to ASCII.
  case name
  of "word":
    result.restrict = uarWord
    result.restrictCls = pcWord
  of "digit":
    result.restrict = uarDigit
    result.restrictCls = pcDigit
  of "space", "white_space":
    result.restrict = uarSpace
    result.restrictCls = pcSpace
  of "alpha":
    result.restrict = uarPosix
    result.restrictCls = pcAlpha
  of "alnum":
    result.restrict = uarPosix
    result.restrictCls = pcAlnum
  of "upper":
    result.restrict = uarPosix
    result.restrictCls = pcUpper
  of "lower":
    result.restrict = uarPosix
    result.restrictCls = pcLower
  of "print":
    result.restrict = uarPosix
    result.restrictCls = pcPrint
  of "graph":
    result.restrict = uarPosix
    result.restrictCls = pcGraph
  of "blank":
    result.restrict = uarPosix
    result.restrictCls = pcBlank
  of "cntrl":
    result.restrict = uarPosix
    result.restrictCls = pcCntrl
  of "xdigit":
    result.restrict = uarPosix
    result.restrictCls = pcXdigit
  of "ascii":
    result.restrict = uarPosix
    result.restrictCls = pcAscii
  # \p{Punct} is the General_Category, not a ctype, so (?P) leaves it alone;
  # \p{PosixPunct} is the ctype and does follow (?P).  The other \p{Posix*}
  # aliases are reni extensions that track their [[:...:]] spelling.
  of "posixpunct":
    result.restrict = uarPosix
    result.restrictCls = pcPunct
  of "posixalnum":
    result.restrict = uarPosix
    result.restrictCls = pcAlnum
  of "posixalpha":
    result.restrict = uarPosix
    result.restrictCls = pcAlpha
  of "posixblank":
    result.restrict = uarPosix
    result.restrictCls = pcBlank
  of "posixcntrl":
    result.restrict = uarPosix
    result.restrictCls = pcCntrl
  of "posixgraph":
    result.restrict = uarPosix
    result.restrictCls = pcGraph
  of "posixlower":
    result.restrict = uarPosix
    result.restrictCls = pcLower
  of "posixprint":
    result.restrict = uarPosix
    result.restrictCls = pcPrint
  of "posixupper":
    result.restrict = uarPosix
    result.restrictCls = pcUpper
  of "posixxdigit":
    result.restrict = uarPosix
    result.restrictCls = pcXdigit
  # (?W)/(?D)/(?S) reach these three, exactly as they reach the brackets.
  of "posixword":
    result.restrict = uarWord
    result.restrictCls = pcWord
  of "posixdigit":
    result.restrict = uarDigit
    result.restrictCls = pcDigit
  of "posixspace":
    result.restrict = uarSpace
    result.restrictCls = pcSpace
  else:
    discard

proc asciiRestricted(p: UniProp, flags: RegexFlags): bool {.inline.} =
  case p.restrict
  of uarNone:
    false
  of uarWord:
    rfAsciiWord in flags or rfAsciiPosix in flags
  of uarDigit:
    rfAsciiDigit in flags or rfAsciiPosix in flags
  of uarSpace:
    rfAsciiSpace in flags or rfAsciiPosix in flags
  of uarPosix:
    rfAsciiPosix in flags

proc matchUnicodeProp*(r: Rune, p: UniProp, flags: RegexFlags = {}): bool =
  ## Match a resolved ``\p{...}`` property.  See ``resolveUnicodeProp``.
  if asciiRestricted(p, flags):
    return matchPosixClass(r, p.restrictCls, true)
  case p.kind
  of upNever:
    false
  of upAlways:
    true
  of upCategory:
    unicodeCategory(r) in UnicodeCategorySet(p.catBits)
  of upTypeMask:
    UnicodeTypeMask(p.typeBits) in unicodeTypes(r)
  of upPosix:
    matchPosixClass(r, p.posixCls, false)
  of upWord:
    isWordChar(r, false)
  of upAscii:
    int32(r) >= 0 and int32(r) <= 127
  of upEmoji:
    inRangeTable(int32(r), EmojiRanges)
  of upExtPict:
    inRangeTable(int32(r), ExtPictRanges)
  of upBlock:
    int32(r) in blockRanges[int(p.blockIdx)]
  of upScript:
    r.isCodePoint and int(unicodeScript(r)) == int(p.scriptId)

proc graphemeBreakProp*(r: Rune): GcbProp =
  let cp = int32(r)
  # Single-value checks first
  if cp == 0x000D:
    return gcbCR
  if cp == 0x000A:
    return gcbLF
  if cp == 0x200D:
    return gcbZWJ
  # Control (CR and LF are excluded from the table by the checks above)
  if inRangeTable(cp, ControlRanges):
    return gcbControl
  # Regional Indicator
  if cp >= 0x1F1E6 and cp <= 0x1F1FF:
    return gcbRegionalIndicator
  # Hangul Jamo (Leading / Vowel / Trailing)
  if inRangeTable(cp, HangulLRanges):
    return gcbL
  if inRangeTable(cp, HangulVRanges):
    return gcbV
  if inRangeTable(cp, HangulTRanges):
    return gcbT
  # Hangul Syllable (LV or LVT)
  if cp >= HangulSBase and cp < HangulSBase + HangulSCount:
    if (cp - HangulSBase) mod HangulTCount == 0:
      return gcbLV
    else:
      return gcbLVT
  # Prepend
  if inRangeTable(cp, PrependRanges):
    return gcbPrepend
  # SpacingMark: the table is the exact GCB=SpacingMark set, which also
  # covers U+0E33 and U+0EB3 (General_Category Lo, not Mc).
  if inRangeTable(cp, SpacingMarkRanges):
    return gcbSpacingMark
  # Extend: the table is the exact GCB=Extend set, so no general-category
  # fallback is needed - every Cf that is not Extend is Control or Prepend.
  if inRangeTable(cp, ExtendRanges):
    return gcbExtend
  gcbOther

proc nextCharAt*(s: openArray[char], p: var int, r: var Rune) {.inline.} =
  ## Decode the character at ``p`` and advance past it, under the same length
  ## rule the matcher and the scan loops use.  A sequence truncated by the end
  ## of ``s`` is not a character, so its lead byte stands for itself; the
  ## segmentation algorithms below only need to keep making progress there.
  var code: int32
  var np: int
  if decodeAt(s, p, code, np):
    r = Rune(code)
    p = np
  else:
    r = Rune(int32(s[p].uint8))
    inc p

proc isGraphemeBoundary*(subject: openArray[char], pos: int): bool =
  ## Determine if there is a grapheme cluster boundary at byte position `pos`
  ## in `subject`. Returns true at string boundaries and at grapheme breaks.
  ## Implements UAX #29 grapheme cluster boundary rules (simplified).
  if pos <= 0 or pos >= subject.len:
    return true
  # Decode the rune just before pos and at pos
  var prevStart: int
  let prevRune = Rune(prevCharAt(subject, pos, prevStart))
  var curPos = pos
  var curRune: Rune
  if curPos < subject.len:
    nextCharAt(subject, curPos, curRune)
  else:
    return true
  let prev = graphemeBreakProp(prevRune)
  let cur = graphemeBreakProp(curRune)
  # GB3: Do not break between CR and LF
  if prev == gcbCR and cur == gcbLF:
    return false
  # GB4: Break after controls
  if prev in {gcbControl, gcbCR, gcbLF}:
    return true
  # GB5: Break before controls
  if cur in {gcbControl, gcbCR, gcbLF}:
    return true
  # GB6: Do not break Hangul syllable sequences (L × (L | V | LV | LVT))
  if prev == gcbL and cur in {gcbL, gcbV, gcbLV, gcbLVT}:
    return false
  # GB7: (LV | V) × (V | T)
  if prev in {gcbLV, gcbV} and cur in {gcbV, gcbT}:
    return false
  # GB8: (LVT | T) × T
  if prev in {gcbLVT, gcbT} and cur == gcbT:
    return false
  # GB9: × (Extend | ZWJ)
  if cur in {gcbExtend, gcbZWJ}:
    return false
  # GB9a: × SpacingMark
  if cur == gcbSpacingMark:
    return false
  # GB9b: Prepend ×
  if prev == gcbPrepend:
    return false
  # GB11: \p{Extended_Pictographic} Extend* ZWJ × \p{Extended_Pictographic}
  if prev == gcbZWJ and inRangeTable(int32(curRune), ExtPictRanges):
    # Check that before the ZWJ there is ExtPict followed by zero or more Extends
    var scanPos = prevStart
    while scanPos > 0:
      var sp: int
      let r2 = Rune(prevCharAt(subject, scanPos, sp))
      let prop = graphemeBreakProp(r2)
      if prop == gcbExtend:
        scanPos = sp
        continue
      if inRangeTable(int32(r2), ExtPictRanges):
        return false # GB11 applies
      break
    # GB11 does not apply if no ExtPict found before ZWJ
  # GB12/GB13: Regional_Indicator handling (pairs)
  if prev == gcbRegionalIndicator and cur == gcbRegionalIndicator:
    # Count preceding RI characters
    var riCount = 0
    var scanPos = prevStart
    while scanPos > 0:
      var sp: int
      let r2 = Rune(prevCharAt(subject, scanPos, sp))
      if graphemeBreakProp(r2) != gcbRegionalIndicator:
        break
      inc riCount
      scanPos = sp
    # Don't break if odd number of RI before (makes a pair)
    if riCount mod 2 == 0:
      return false
    return true
  # GB999: Otherwise, break
  true

proc nextGraphemeClusterEnd*(subject: openArray[char], pos: int): int =
  ## Return the byte position just past the end of the grapheme cluster
  ## starting at `pos`.
  if pos >= subject.len:
    return pos
  var p = pos
  var r: Rune
  nextCharAt(subject, p, r)
  # Consume following characters that don't form a boundary
  while p < subject.len:
    if isGraphemeBoundary(subject, p):
      break
    nextCharAt(subject, p, r)
  p

const
  # Word_Break=ALetter or Hebrew_Letter (AHLetter in UAX #29).  unicodedb
  # folds the code points that are both ALetter and Extended_Pictographic into
  # one value: they count as letters here, while WB3c asks ExtPictRanges the
  # way Oniguruma consults Extended_Pictographic directly.
  AHLetterProps = {sgwAletter, sgwHebrewLetter, sgwAletterExtendedPictographic}

proc isWordBoundaryUax29*(subject: openArray[char], pos: int): bool =
  ## Determine if there is a word boundary at byte position `pos`
  ## per UAX #29 word break rules. Returns true at string boundaries.
  if pos <= 0 or pos >= subject.len:
    return true
  # Decode runes before and at pos
  var prevStart: int
  let prevRune = Rune(prevCharAt(subject, pos, prevStart))
  var curPos = pos
  var curRune: Rune
  nextCharAt(subject, curPos, curRune)
  let prev = wordBreakProp(prevRune)
  let cur = wordBreakProp(curRune)
  # WB3: Do not break between CR and LF
  if prev == sgwCr and cur == sgwLf:
    return false
  # WB3a/WB3b: Break after/before newlines
  if prev in {sgwCr, sgwLf, sgwNewline}:
    return true
  if cur in {sgwCr, sgwLf, sgwNewline}:
    return true
  # WB3c: ZWJ × \p{Extended_Pictographic}
  if prev == sgwZwj and inRangeTable(int32(curRune), ExtPictRanges):
    return false
  # WB3d: WSegSpace × WSegSpace
  if prev == sgwWsegSpace and cur == sgwWsegSpace:
    return false
  # WB4: Skip Extend/Format/ZWJ (treat as transparent)
  # Get the "effective" previous property (skip Extend/Format/ZWJ)
  var effPrev = prev
  var effPrevRune = prevRune
  # Where ``effPrevRune`` starts.  The look-back loops below must scan from
  # here, not from ``prevStart``: when WB4 skipped an Extend/Format/ZWJ run,
  # stepping back from ``prevStart`` lands on ``effPrevRune`` itself.
  var effPrevStart = prevStart
  if effPrev in {sgwExtend, sgwFormat, sgwZwj}:
    var sp = prevStart
    while sp > 0:
      var sp2: int
      let r2 = Rune(prevCharAt(subject, sp, sp2))
      let p2 = wordBreakProp(r2)
      if p2 notin {sgwExtend, sgwFormat, sgwZwj}:
        effPrev = p2
        effPrevRune = r2
        effPrevStart = sp2
        break
      sp = sp2
  # WB5: AHLetter × AHLetter
  let isAHPrev = effPrev in AHLetterProps
  let isAHCur = cur in AHLetterProps
  if isAHPrev and isAHCur:
    return false
  # WB6: AHLetter × (MidLetter | MidNumLetQ) AHLetter
  if isAHPrev and cur in {sgwMidLetter, sgwMidNumLet, sgwSingleQuote}:
    # Look ahead: is the char after cur an AHLetter?
    var np = curPos
    # Skip the current char (already consumed by fastRuneAt above)
    # Skip Extend/Format/ZWJ
    while np < subject.len:
      var r2: Rune
      var np2 = np
      nextCharAt(subject, np2, r2)
      let p2 = wordBreakProp(r2)
      if p2 notin {sgwExtend, sgwFormat, sgwZwj}:
        if p2 in AHLetterProps:
          return false
        break
      np = np2
  # WB7: AHLetter (MidLetter | MidNumLetQ) × AHLetter
  if isAHCur and effPrev in {sgwMidLetter, sgwMidNumLet, sgwSingleQuote}:
    # Look back further: is the char before effPrev an AHLetter?
    var sp = effPrevStart
    while sp > 0:
      var sp2: int
      let r2 = Rune(prevCharAt(subject, sp, sp2))
      let p2 = wordBreakProp(r2)
      if p2 notin {sgwExtend, sgwFormat, sgwZwj}:
        if p2 in AHLetterProps:
          return false
        break
      sp = sp2
  # WB7a: Hebrew_Letter × Single_Quote
  if effPrev == sgwHebrewLetter and cur == sgwSingleQuote:
    return false
  # WB7b: Hebrew_Letter × Double_Quote Hebrew_Letter
  if effPrev == sgwHebrewLetter and cur == sgwDoubleQuote:
    var np = curPos
    while np < subject.len:
      var r2: Rune
      var np2 = np
      nextCharAt(subject, np2, r2)
      let p2 = wordBreakProp(r2)
      if p2 notin {sgwExtend, sgwFormat, sgwZwj}:
        if p2 == sgwHebrewLetter:
          return false
        break
      np = np2
  # WB7c: Hebrew_Letter Double_Quote × Hebrew_Letter
  if cur == sgwHebrewLetter and effPrev == sgwDoubleQuote:
    var sp = effPrevStart
    while sp > 0:
      var sp2: int
      let r2 = Rune(prevCharAt(subject, sp, sp2))
      let p2 = wordBreakProp(r2)
      if p2 notin {sgwExtend, sgwFormat, sgwZwj}:
        if p2 == sgwHebrewLetter:
          return false
        break
      sp = sp2
  # WB8: Numeric × Numeric
  if effPrev == sgwNumeric and cur == sgwNumeric:
    return false
  # WB9: AHLetter × Numeric
  if isAHPrev and cur == sgwNumeric:
    return false
  # WB10: Numeric × AHLetter
  if effPrev == sgwNumeric and isAHCur:
    return false
  # WB11: Numeric (MidNum | MidNumLetQ) × Numeric
  if cur == sgwNumeric and effPrev in {sgwMidNum, sgwMidNumLet, sgwSingleQuote}:
    var sp = effPrevStart
    while sp > 0:
      var sp2: int
      let r2 = Rune(prevCharAt(subject, sp, sp2))
      let p2 = wordBreakProp(r2)
      if p2 notin {sgwExtend, sgwFormat, sgwZwj}:
        if p2 == sgwNumeric:
          return false
        break
      sp = sp2
  # WB12: Numeric × (MidNum | MidNumLetQ) Numeric
  if effPrev == sgwNumeric and cur in {sgwMidNum, sgwMidNumLet, sgwSingleQuote}:
    var np = curPos
    while np < subject.len:
      var r2: Rune
      var np2 = np
      nextCharAt(subject, np2, r2)
      let p2 = wordBreakProp(r2)
      if p2 notin {sgwExtend, sgwFormat, sgwZwj}:
        if p2 == sgwNumeric:
          return false
        break
      np = np2
  # WB13: Katakana × Katakana
  if effPrev == sgwKatakana and cur == sgwKatakana:
    return false
  # WB13a: (AHLetter | Numeric | Katakana | ExtendNumLet) × ExtendNumLet
  if cur == sgwExtendNumLet and
      effPrev in AHLetterProps + {sgwNumeric, sgwKatakana, sgwExtendNumLet}:
    return false
  # WB13b: ExtendNumLet × (AHLetter | Numeric | Katakana)
  if effPrev == sgwExtendNumLet and cur in AHLetterProps + {sgwNumeric, sgwKatakana}:
    return false
  # WB15/WB16: Regional Indicator handling (pairs)
  if effPrev == sgwRegionalIndicator and cur == sgwRegionalIndicator:
    var riCount = 0
    var sp = effPrevStart
    while sp > 0:
      var sp2: int
      let r2 = Rune(prevCharAt(subject, sp, sp2))
      let p2 = wordBreakProp(r2)
      if p2 notin {sgwExtend, sgwFormat, sgwZwj}:
        if p2 != sgwRegionalIndicator:
          break
        inc riCount
      sp = sp2
    if riCount mod 2 == 0:
      return false
    return true
  # WB4: × (Extend | Format | ZWJ)
  if cur in {sgwExtend, sgwFormat, sgwZwj}:
    return false
  # WB999: Otherwise, break
  return true

proc nextWordSegmentEnd*(subject: openArray[char], pos: int): int =
  ## Return the byte position just past the end of the word segment
  ## starting at `pos` (per UAX #29 word boundaries).
  if pos >= subject.len:
    return pos
  var p = pos
  var r: Rune
  nextCharAt(subject, p, r)
  while p < subject.len:
    if isWordBoundaryUax29(subject, p):
      break
    nextCharAt(subject, p, r)
  return p

proc caseInsensitiveMatch*(r, target: Rune, flags: RegexFlags): bool =
  ## Case-insensitive comparison respecting rfIgnoreCaseAscii flag.
  if rfIgnoreCase notin flags:
    return r == target
  if rfIgnoreCaseAscii in flags:
    # ASCII-only: only fold if both are ASCII
    if int32(r) <= 127 and int32(target) <= 127:
      return simpleFold(r) == simpleFold(target)
    return r == target
  simpleFold(r) == simpleFold(target)

proc matchCcAtom*(r: Rune, atom: CcAtom, flags: RegexFlags): bool =
  case atom.kind
  of ccLiteral:
    r == atom.rune or caseInsensitiveMatch(r, atom.rune, flags)
  of ccRange:
    let lo = int32(atom.rangeFrom)
    let hi = int32(atom.rangeTo)
    let ri = int32(r)
    if ri >= lo and ri <= hi:
      true
    elif rfIgnoreCase in flags:
      if rfIgnoreCaseAscii in flags:
        # ASCII-only: the subject and the variant it folds to must both be
        # ASCII, so ``k`` never reaches U+212A and U+212A never reaches ``k``.
        #
        # Walk the variants rather than folding once.  A range is not a value
        # that can be folded alongside the subject the way [caseInsensitiveMatch]
        # folds both sides of a literal, and ``simpleFold`` maps toward one
        # case only -- testing it against the range's own endpoints answers
        # only for a range written in that case, so ``[a-z]`` would match ``Y``
        # while ``[A-Z]`` missed ``y``.
        if ri <= 127:
          for variant in caseFoldVariants(r):
            let vi = int32(variant)
            if vi <= 127 and vi >= lo and vi <= hi:
              return true
          false
        else:
          false
      else:
        # Check if any case variant of r falls in the original range
        for variant in caseFoldVariants(r):
          if int32(variant) >= lo and int32(variant) <= hi:
            return true
        false
    else:
      false
  of ccCharType:
    case atom.charType
    of ctWord:
      # Inside [...] Oniguruma uses the raw CR_Word ranges: no Latin-1 extras.
      isWordChar(r, rfAsciiWord in flags or rfAsciiPosix in flags, latin1Digits = false)
    of ctNotWord:
      not isWordChar(
        r, rfAsciiWord in flags or rfAsciiPosix in flags, latin1Digits = false
      )
    of ctDigit:
      isDigitChar(r, rfAsciiDigit in flags or rfAsciiPosix in flags)
    of ctNotDigit:
      not isDigitChar(r, rfAsciiDigit in flags or rfAsciiPosix in flags)
    of ctSpace:
      isSpaceChar(r, rfAsciiSpace in flags or rfAsciiPosix in flags)
    of ctNotSpace:
      not isSpaceChar(r, rfAsciiSpace in flags or rfAsciiPosix in flags)
    of ctHexDigit:
      isHexDigitChar(r)
    of ctNotHexDigit:
      not isHexDigitChar(r)
    of ctDot, ctAnyChar:
      true
    of ctNotNewline:
      r != Rune(0x0A)
    of ctNewlineSeq:
      let c = int32(r)
      c == 0x0A or c == 0x0D or c == 0x0B or c == 0x0C or c == 0x85 or c == 0x2028 or
        c == 0x2029
    of ctGraphemeCluster:
      true # \X in character classes: any character
  of ccPosix:
    matchPosixClass(r, atom.posixClass, posixAsciiOnly(atom.posixClass, flags))
  of ccNegPosix:
    not matchPosixClass(r, atom.posixClass, posixAsciiOnly(atom.posixClass, flags))
  of ccUnicodeProp:
    matchUnicodeProp(r, atom.prop, flags)
  of ccNegUnicodeProp:
    not matchUnicodeProp(r, atom.prop, flags)
  of ccNestedClass:
    var anyMatch = false
    for nested in atom.nestedAtoms:
      if matchCcAtom(r, nested, flags):
        anyMatch = true
        break
    if atom.nestedNegated:
      not anyMatch
    else:
      anyMatch
  of ccIntersection:
    # Character must match BOTH left and right sides
    var leftMatch = false
    for a in atom.interLeft:
      if matchCcAtom(r, a, flags):
        leftMatch = true
        break
    if atom.interLeftNeg:
      leftMatch = not leftMatch
    var rightMatch = false
    for a in atom.interRight:
      if matchCcAtom(r, a, flags):
        rightMatch = true
        break
    if atom.interRightNeg:
      rightMatch = not rightMatch
    leftMatch and rightMatch

const AsciiRestrictFlags = {rfAsciiWord, rfAsciiDigit, rfAsciiSpace, rfAsciiPosix}
  ## The flags a class atom can read below U+0080.  Each only ever turns some
  ## test's ``asciiOnly`` argument on (``posixAsciiOnly`` and
  ## ``asciiRestricted`` are disjunctions over this set), so all four set and
  ## none set are the two extremes: an atom that answers the same at both ends
  ## answers the same for every combination in between.  ``rfIgnoreCase`` is
  ## out of reach here, since the matcher gates the bitset on its absence.

proc atomAsciiFlagInvariant(atom: CcAtom): bool =
  ## Whether ``atom`` reads every ASCII code point the same however the
  ## ASCII-restriction flags are set.
  ##
  ## Only a ``\p{...}`` can answer no.  Every other atom settles its ASCII
  ## answer before the flags are consulted: ``ccLiteral`` and ``ccRange`` never
  ## read one, and ``matchPosixClass`` / ``isWordChar`` / ``isDigitChar`` /
  ## ``isSpaceChar`` return from their ASCII tables above ``asciiOnly``.  A
  ## restriction does not narrow a property, it swaps it for ``restrictCls``,
  ## and nothing makes those two agree below U+0080.
  ##
  ## Today they do agree, so this probe rejects no atom and no test exercises
  ## a rejection; it is here for the pairing that stops agreeing (a table
  ## regenerated against a newer Unicode, or a ``restrictCls`` pointed at a
  ## ctype that differs in the ASCII range).  Composites are checked child by
  ## child: checking only the whole could miss two children that cancel at
  ## both ends and disagree in between.
  case atom.kind
  of ccNestedClass:
    for nested in atom.nestedAtoms:
      if not atomAsciiFlagInvariant(nested):
        return false
    true
  of ccIntersection:
    for a in atom.interLeft:
      if not atomAsciiFlagInvariant(a):
        return false
    for a in atom.interRight:
      if not atomAsciiFlagInvariant(a):
        return false
    true
  of ccUnicodeProp, ccNegUnicodeProp:
    if atom.prop.restrict == uarNone:
      return true
    for cp in 0'i32 .. 127'i32:
      let r = Rune(cp)
      if matchCcAtom(r, atom, {}) != matchCcAtom(r, atom, AsciiRestrictFlags):
        return false
    true
  else:
    true

proc exactAsciiClassSet*(atoms: seq[CcAtom], s: var set[uint8]): bool =
  ## The ASCII bytes ``atoms`` match, *before* negation, or false when that
  ## set is not exact.  Each byte is asked of the atoms themselves rather than
  ## derived from their shape, so a ``\p{...}``, a nested class and an
  ## intersection answer here too -- which the shape-reading
  ## [classAsciiMatches] cannot do, hence this fallback.  A class an
  ## ASCII-restriction flag can move gives up instead: those flags are
  ## switched on inside the pattern, and no compile-time set stands for both
  ## readings.
  for atom in atoms:
    if not atomAsciiFlagInvariant(atom):
      return false
  s = {}
  for cp in 0'i32 .. 127'i32:
    let r = Rune(cp)
    for atom in atoms:
      if matchCcAtom(r, atom, {}):
        s.incl(uint8(cp))
        break
  true
