name: Docs

on:
  push:
    paths:
      - '.github/workflows/docs.yml'
      - 'reni.nim'
      - 'reni/**'
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Setup Nim
      uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: 'stable'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install deps
      run: |
        nimble install --depsOnly

    - name: Gen docs
      run: |
        nim doc --project --index:on --outdir:./htmldocs ./reni.nim

    - uses: actions/upload-pages-artifact@v4
      with:
        path: ./htmldocs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/deploy-pages@v4
